### ISSUE TITLE
Compiled GUI executable crashes on wallet creation

### ISSUE THREAD

**Issue by mikakoi** [Codaone/DEXBot#10]
Executable created with pyinstaller compiles but crashes on wallet creation.
This is the error message:
```
Traceback (most recent call last):
  File "dexbot/views/create_wallet.py", line 19, in validate_form
  File "dexbot/controllers/wallet_controller.py", line 14, in create_wallet
  File "site-packages/bitshares-0.1.11b0-py3.5.egg/bitshares/wallet.py", line 170, in create
  File "site-packages/bitshares-0.1.11b0-py3.5.egg/bitshares/wallet.py", line 177, in newWallet
  File "site-packages/bitshares-0.1.11b0-py3.5.egg/bitshares/storage.py", line 393, in __init__
  File "site-packages/bitshares-0.1.11b0-py3.5.egg/bitshares/storage.py", line 414, in saveEncrytpedMaster
  File "site-packages/bitshares-0.1.11b0-py3.5.egg/bitshares/storage.py", line 438, in getEncryptedMaster
  File "site-packages/bitshares-0.1.11b0-py3.5.egg/bitshares/aes.py", line 33, in encrypt
  File "site-packages/pycryptodome-3.4.7-py3.5-linux-x86_64.egg/Crypto/Cipher/AES.py", line 202, in new
  File "site-packages/pycryptodome-3.4.7-py3.5-linux-x86_64.egg/Crypto/Cipher/__init__.py", line 55, in _create_cipher
  File "site-packages/pycryptodome-3.4.7-py3.5-linux-x86_64.egg/Crypto/Cipher/_mode_cbc.py", line 247, in _create_cbc_cipher
  File "site-packages/pycryptodome-3.4.7-py3.5-linux-x86_64.egg/Crypto/Cipher/_mode_cbc.py", line 95, in __init__
AttributeError: 'NoneType' object has no attribute 'CBC_start_operation'
Aborted (core dumped)
```

**Comment by svdev** [comment]
@mikakoi I believe this is fixed by applying the changes to `hooks/hook-Crypto.py` as done in https://github.com/Codaone/DEXBot/pull/24/commits/05d2b279c64bc792a13dce542d655b837cbf1d3e

**Comment by MarkoPaasila** [comment]
Issue 22 apparently covers this issue, so I labeled it as "Status: Abandoned".

**Comment by mikakoi** [comment]
Closing this because Issue 22 already covers this
