### ISSUE TITLE
can not add UIA assets trade work like GDEX.EOS ,GDEX.SEER and so on

### ISSUE THREAD

**Issue by hiquanta** [Codaone/DEXBot#103]
error on cny:gdex.eos market and log this:
Error in on_market: 'u-bts'

Traceback (most recent call last):
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitsharesapi/websocket.py", line 276, in on_message
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitsharesapi/websocket.py", line 276, in <listcomp>
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/shes/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitshares/notify.py", line 159, in process_market
    blockchain_instance=self.blockchain
  File "/home/shes/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/shes/.local/lib/python3.5/site-packages/dexbot-0.1.16-py3.5.egg/dexbot/worker.py", line 129, in on_market
    if self.workers[worker_name].disabled:
KeyError: 'u-bts'

**Comment by MarkoPaasila** [comment]
@hiquanta is this still a problem?

**Comment by MarkoPaasila** [comment]
I'll close this but we can re-open if we get more information
