### ISSUE TITLE
Bot crashes with error after edit when restarting a worker 

### ISSUE THREAD

**Issue by juhanihaapala** [Codaone/DEXBot#109]
Stack trace of the error
```
Traceback (most recent call last):
  File "/dexbot/dexbot/views/worker_item.py", line 52, in start_worker
    self.main_ctrl.create_worker(self.worker_name, self.worker_config, self.view)
  File "/dexbot/dexbot/controllers/main_controller.py", line 29, in create_worker
    self.worker_manager.add_worker(worker_name, config)
  File "/dexbot/dexbot/worker.py", line 161, in add_worker
    self.update_notify()
  File "/dexbot/dexbot/worker.py", line 93, in update_notify
    self.notify.reset_subscriptions(list(self.accounts), list(self.markets))
  File "/dexbot/venv/lib/python3.5/site-packages/events/events.py", line 58, in __getattr__
    raise EventsException("Event '%s' is not declared" % name)
events.events.EventsException: Event 'reset_subscriptions' is not declared
Aborted (core dumped)
```

**Comment by MarkoPaasila** [comment]
@juhanihaapala can this be closed?

**Comment by MarkoPaasila** [comment]
I'll abandon this bug. It's old and has likely been solved by other fixes.
