### ISSUE TITLE
Windows user cant get worker to place orders

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#111]
## Expected Behavior
Worker to place orders

## Actual Behavior
Worker does not place orders, the following error occurred:

![github](https://user-images.githubusercontent.com/33036236/39617263-f0041d70-4f76-11e8-9bcd-11ca22eee228.jpg)

By unchecking the relative order box and setting a manual order size, this was fixed and the worker started placing orders.

## Specifications

  - Version: 0.1.16 
  - OS: Windows 7 64bit pro

**Comment by ashisht24** [comment]
![photo_2018-05-04_23-06-38](https://user-images.githubusercontent.com/38988375/39642628-f44f9ab6-4fef-11e8-8d5a-141b0f285e92.jpg)

below is the log file text. This is what i am getting and its most recent log. it executes one order (buy or sell) and then does not cancel the other and place a new buy and sell orders at a new price point.

TypeError: unsupported operand type(s) for /: 'int' and 'str'
2018-05-04 15:02:54,229 - Ashish using account ashisht24 on BRIDGE.XVG/BRIDGE.BTC - INFO - Canceling all orders
2018-05-04 15:03:03,182 - Ashish using account ashisht24 on BRIDGE.XVG/BRIDGE.BTC - INFO - Change detected, updating orders
2018-05-04 15:03:12,174 - Ashish using account ashisht24 on BRIDGE.XVG/BRIDGE.BTC - INFO - Placed a buy order for 0.000121625 BRIDGE.BTC @ 7.99680443407148e-06
2018-05-04 15:03:18,473 - Ashish using account ashisht24 on BRIDGE.XVG/BRIDGE.BTC - INFO - Placed a sell order for 22.23563793 BRIDGE.XVG @ 8.323204615053989e-06
2018-05-04 15:03:19,063 - Ashish using account ashisht24 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "dexbot\worker.py", line 74, in init_workers
  File "dexbot\strategies\relative_orders.py", line 38, in __init__
  File "dexbot\strategies\relative_orders.py", line 152, in check_orders
  File "dexbot\strategies\relative_orders.py", line 167, in update_gui_slider
  File "dexbot\basestrategy.py", line 317, in total_balance
  File "dexbot\basestrategy.py", line 339, in orders_balance
  File "dexbot\basestrategy.py", line 173, in get_updated_order
  File "dexbot\basestrategy.py", line 190, in updated_open_orders
TypeError: unsupported operand type(s) for /: 'str' and 'int'
2018-05-04 21:39:19,882 - Ashish using account ashisht24 on BRIDGE.XVG/BRIDGE.BTC - INFO - Change detected, updating orders
2018-05-04 21:39:20,198 - Ashish using account ashisht24 on BRIDGE.XVG/BRIDGE.BTC - INFO - Canceling all orders
2018-05-04 21:39:37,113 - Ashish using account ashisht24 on BRIDGE.XVG/BRIDGE.BTC - INFO - Placed a buy order for 0.000213975 BRIDGE.BTC @ 8.236896631515905e-06
2018-05-04 21:39:49,196 - Ashish using account ashisht24 on BRIDGE.XVG/BRIDGE.BTC - INFO - Placed a sell order for 11.117818965 BRIDGE.XVG @ 8.573096494026759e-06
2018-05-04 21:39:50,198 - Ashish using account ashisht24 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "dexbot\worker.py", line 74, in init_workers
  File "dexbot\strategies\relative_orders.py", line 38, in __init__
  File "dexbot\strategies\relative_orders.py", line 152, in check_orders
  File "dexbot\strategies\relative_orders.py", line 167, in update_gui_slider
  File "dexbot\basestrategy.py", line 317, in total_balance
  File "dexbot\basestrategy.py", line 339, in orders_balance
  File "dexbot\basestrategy.py", line 173, in get_updated_order
  File "dexbot\basestrategy.py", line 190, in updated_open_orders
TypeError: unsupported operand type(s) for /: 'int' and 'str'
2018-05-04 22:14:26,769 - Ashish using account ashisht24 on BRIDGE.XVG/BRIDGE.BTC - INFO - Change detected, updating orders
2018-05-04 22:14:27,020 - Ashish using account ashisht24 on BRIDGE.XVG/BRIDGE.BTC - INFO - Canceling all orders
2018-05-04 22:14:40,317 - Ashish using account ashisht24 on BRIDGE.XVG/BRIDGE.BTC - INFO - Placed a buy order for 0.00010699 BRIDGE.BTC @ 7.942863684287901e-06
2018-05-04 22:14:49,269 - Ashish using account ashisht24 on BRIDGE.XVG/BRIDGE.BTC - INFO - Placed a sell order for 24.080653125 BRIDGE.XVG @ 8.267062202013938e-06
2018-05-04 22:14:49,826 - Ashish using account ashisht24 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "dexbot\worker.py", line 74, in init_workers
  File "dexbot\strategies\relative_orders.py", line 38, in __init__
  File "dexbot\strategies\relative_orders.py", line 152, in check_orders
  File "dexbot\strategies\relative_orders.py", line 167, in update_gui_slider
  File "dexbot\basestrategy.py", line 317, in total_balance
  File "dexbot\basestrategy.py", line 339, in orders_balance
  File "dexbot\basestrategy.py", line 173, in get_updated_order
  File "dexbot\basestrategy.py", line 190, in updated_open_orders
TypeError: unsupported operand type(s) for /: 'str' and 'int'
2018-05-04 22:18:40,121 - Ashish using account ashisht24 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "dexbot\worker.py", line 74, in init_workers
  File "dexbot\strategies\relative_orders.py", line 38, in __init__
  File "dexbot\strategies\relative_orders.py", line 137, in check_orders
  File "dexbot\basestrategy.py", line 173, in get_updated_order
  File "dexbot\basestrategy.py", line 190, in updated_open_orders
TypeError: unsupported operand type(s) for /: 'str' and 'int'

**Comment by ashisht24** [comment]
![capture](https://user-images.githubusercontent.com/38988375/39643083-2bcc074e-4ff1-11e8-987e-edc466d3d7fc.JPG)

**Comment by ashisht24** [comment]
have downloaded the latest version 1.21 installed it by just double clicking. rest all was the same as version 1.16. Still the same below issue.

 it fills one order (buy or sell) and then does not cancel the other and place a new buy and sell orders at a new price point.

for example if i start the bot and press play button, in few seconds it will place buy and sell orders. Now the buy gets filled but the sell does not. the sell order remains as it is or vice e versa the bot doesnt do anything as expected. (cancel the sell and place a new buy and sell orders at a new price level)

then i have to cancel the sell order manually and restart the bot or pause and play the bot for new buy sell orders

**Comment by mikakoi** [comment]
@ashisht24 your error doesn't seem to be the same as cryptoking is getting. And your error seems to be reported here #115

**Comment by MarkoPaasila** [comment]
No those are not fixed yet.

**Comment by MarkoPaasila** [comment]
I'll close this as @ashisht24 reports that the bot is placing orders.
