### ISSUE TITLE
DEXBot Stopped placing orders

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#112]
## Expected Behavior
Left a worker running, expected it to be still running

## Actual Behavior
Worker stopped placing orders and the following error occurred on the terminal:

`close status: 31522
Traceback (most recent call last):
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.16-py3.5.egg/dexbot/views/worker_item.py", line 118, in handle_edit_worker
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.16-py3.5.egg/dexbot/views/worker_item.py", line 105, in reload_widget
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.16-py3.5.egg/dexbot/views/worker_item.py", line 40, in setup_ui_data
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.16-py3.5.egg/dexbot/views/worker_item.py", line 78, in set_worker_profit
TypeError: float() argument must be a string or a number, not 'dict'
`

## Specifications

  - Version:0.1.16
  - OS: ubuntu 16.04

**Comment by MarkoPaasila** [comment]
@juhanihaapala did you fix this?

**Comment by mikakoi** [comment]
@CryptoKong Have you been able to reproduce this?

**Comment by MarkoPaasila** [comment]
This is likely a duplicate, and is also old enough to be closed. I am sure that @CryptoKong's bot is running.
