### ISSUE TITLE
on unknown - ERROR - Worker Initialisation

### ISSUE THREAD

**Issue by xemage** [Codaone/DEXBot#115]
After two succesfully placed orders (on BRIDGE.BTC/BRIDGE.XVG) I get this

unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "/home/emage/.local/lib/python3.5/site-packages/dexbot-0.1.19-py3.5.egg/dexbot/worker.py", line 75, in init_workers
    view=self.view
  File "/home/emage/.local/lib/python3.5/site-packages/dexbot-0.1.19-py3.5.egg/dexbot/strategies/relative_orders.py", line 38, in __init__
    self.check_orders()
  File "/home/emage/.local/lib/python3.5/site-packages/dexbot-0.1.19-py3.5.egg/dexbot/strategies/relative_orders.py", line 142, in check_orders
    self.update_gui_slider()
  File "/home/emage/.local/lib/python3.5/site-packages/dexbot-0.1.19-py3.5.egg/dexbot/strategies/relative_orders.py", line 157, in update_gui_slider
    total_balance = self.total_balance(self['order_ids'])
  File "/home/emage/.local/lib/python3.5/site-packages/dexbot-0.1.19-py3.5.egg/dexbot/basestrategy.py", line 347, in total_balance
    orders_balance = self.orders_balance(order_ids)
  File "/home/emage/.local/lib/python3.5/site-packages/dexbot-0.1.19-py3.5.egg/dexbot/basestrategy.py", line 369, in orders_balance
    order = self.get_updated_order(order_id)
  File "/home/emage/.local/lib/python3.5/site-packages/dexbot-0.1.19-py3.5.egg/dexbot/basestrategy.py", line 173, in get_updated_order
    for updated_order in self.updated_open_orders:
  File "/home/emage/.local/lib/python3.5/site-packages/dexbot-0.1.19-py3.5.egg/dexbot/basestrategy.py", line 190, in updated_open_orders
    price = o['sell_price']['base']['amount'] / o['sell_price']['quote']['amount']
TypeError: unsupported operand type(s) for /: 'int' and 'str'

  - Version: 0.1.19
  - OS: Ubuntu 16.04

**Comment by MarkoPaasila** [comment]
Wasn't this already fixed? I remember seeing a commit addressing this one, but couldn't find it.

**Comment by xemage** [comment]
Just tried a BTS/BRIDGE.XVG pair in version 0.2.4
Works so far.
