### ISSUE TITLE
Python errors when starting worker

### ISSUE THREAD

**Issue by coinsmith** [Codaone/DEXBot#117]
after installation start dexbot via ./gui.py
setup worker
start worker, following debug errors occur

## Expected Behavior
Worker starts placing orders

## Actual Behavior
Throws error screens, debug log below. 

  File "/home/user/dexbot/dexbot/worker.py", line 75, in init_workers
    view=self.view
  File "/home/user/dexbot/dexbot/strategies/relative_orders.py", line 38, in __init__
    self.check_orders()
  File "/home/user/dexbot/dexbot/strategies/relative_orders.py", line 138, in check_orders
    self.update_orders()
  File "/home/user/dexbot/dexbot/strategies/relative_orders.py", line 77, in update_orders
    self.calculate_order_prices()
  File "/home/user/dexbot/dexbot/strategies/relative_orders.py", line 65, in calculate_order_prices
    self.buy_price = self.center_price * (1 - (self.worker["spread"] / 2) / 100)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

When I change the relative price to a fixed price (totally not desireable, but for trial and error sake), I get the following error.

Traceback (most recent call last):
  File "/home/user/dexbot/dexbot/worker.py", line 75, in init_workers
    view=self.view
  File "/home/user/dexbot/dexbot/strategies/relative_orders.py", line 38, in __init__
    self.check_orders()
  File "/home/user/dexbot/dexbot/strategies/relative_orders.py", line 138, in check_orders
    self.update_orders()
  File "/home/user/dexbot/dexbot/strategies/relative_orders.py", line 99, in update_orders
    buy_order = self.market_buy(amount_base, self.buy_price)
  File "/home/user/dexbot/dexbot/basestrategy.py", line 320, in market_buy
    returnOrderId="head"
  File "/home/user/.local/lib/python3.5/site-packages/bitshares-0.1.16-py3.5.egg/bitshares/market.py", line 432, in buy
    tx = self.blockchain.finalizeOp(order, account["name"], "active", **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/bitshares-0.1.16-py3.5.egg/bitshares/bitshares.py", line 281, in finalizeOp
    self.txbuffer.sign()
  File "/home/user/.local/lib/python3.5/site-packages/bitshares-0.1.16-py3.5.egg/bitshares/transactionbuilder.py", line 346, in sign
    signedtx.sign(self.wifs, chain=self.blockchain.rpc.chain_params)
  File "/home/user/.local/lib/python3.5/site-packages/bitshares-0.1.16-py3.5.egg/bitsharesbase/signedtransactions.py", line 21, in sign
    return super(Signed_Transaction, self).sign(wifkeys, chain)
  File "/home/user/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/graphenebase/signedtransactions.py", line 186, in sign
    signature = sign_message(self.message, wif)
  File "/home/user/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/graphenebase/ecdsa.py", line 180, in sign_message
    private_key = ec.derive_private_key(int(repr(priv_key), 16), ec.SECP256K1(), default_backend())
AttributeError: module 'cryptography.hazmat.primitives.asymmetric.ec' has no attribute 'derive_private_key'

OS ubuntu 16.04 64bit

**Comment by MarkoPaasila** [comment]
Try `pip3 install --upgrade cryptography` and also see https://github.com/Codaone/DEXBot/wiki/Common-problems

**Comment by coinsmith** [comment]
Tried this. Getting a warning in the debug.log:

"CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead." 

Relative prices (along with relative base price) is now an issue. It seems to work with a fixed floating price and fixed amount (I don't want that, of course, but just trying) However, it says I have 'insufficient BTC balance', while in fact I have 0.004 as a test amount.

**Comment by MarkoPaasila** [comment]
@coinsmith do you have BTS for fee's?

**Comment by coinsmith** [comment]
Yes, 21 to be exact.

**Comment by coinsmith** [comment]
Follow up on this: ubuntu build still not working, same errors.

**Comment by ihaywood3** [comment]
you are actually describing a different bug, please open a new issue and give more description: all the settings you used, and cut/paste the full error reports.

**Comment by coinsmith** [comment]
Ok, closing this. I fiddled around with it and can't believe I actually got it to work. 

Please add in the wiki/manual one needs to run cryptobridge locally on 127.0.0.1:8080 
Also, base asset BRIDGE.BTC is not in the drop down manual and has to be typed in. Cheers.
