### ISSUE TITLE
Windows user unable to get worker to place orders

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#120]
## Expected Behavior
Worker to place orders

## Actual Behavior
Received error saying not enough funds

## Steps to Reproduce the Problem

  1.User created worker fine
  2.Press play on worker
  3.Received error message

## Specifications

  - Version: 1.0.23
  - OS: Windows 64 bit

I double checked the users account and he had enough of both asset and 10BTS for fees.
The following was recorded on the log file:

Traceback (most recent call last):
  File "lib\site-packages\bitshares-0.1.14-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 54, in rpcexec
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: amount_to_sell.amount > 0: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot\worker.py", line 75, in init_workers
  File "dexbot\strategies\relative_orders.py", line 38, in init
  File "dexbot\strategies\relative_orders.py", line 138, in check_orders
  File "dexbot\strategies\relative_orders.py", line 99, in update_orders
  File "dexbot\basestrategy.py", line 320, in market_buy
  File "lib\site-packages\bitshares-0.1.14-py3.5.egg\bitshares\market.py", line 437, in buy
  File "lib\site-packages\bitshares-0.1.14-py3.5.egg\bitshares\bitshares.py", line 293, in finalizeOp
  File "lib\site-packages\bitshares-0.1.14-py3.5.egg\bitshares\transactionbuilder.py", line 387, in broadcast
  File "lib\site-packages\bitshares-0.1.14-py3.5.egg\bitshares\transactionbuilder.py", line 381, in broadcast
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 213, in method
  File "lib\site-packages\bitshares-0.1.14-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: amount_to_sell.amount > 0:

**Comment by bitfag** [comment]
This is not a windows-related. This happens when `market_sell()` or `market_buy()` called with 0 amount. There are only `if self.balance(self.market['quote']) < quote_amount:` check and not for 0 balance.
