### ISSUE TITLE
error worker initialisation

### ISSUE THREAD

**Issue by alcafo** [Codaone/DEXBot#141]
When I start worker USD/BTS or BTS/USD with relative orders strategy I get error worker initialisation but other pairs Ive tried like OPEN.BTC/BTS works fine.

## Error
Traceback (most recent call last):
  File "bitshares-0.1.16-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
  File "graphenelib-0.6.2-py3.6.egg/grapheneapi/graphenewsrpc.py", line 174, in rpcexec
grapheneapi.exceptions.RPCError: irrelevant signature included: Unnecessary signature(s) detected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot/worker.py", line 75, in init_workers
  File "dexbot/strategies/relative_orders.py", line 40, in __init__
  File "dexbot/strategies/relative_orders.py", line 130, in check_orders
  File "dexbot/strategies/relative_orders.py", line 101, in update_orders
  File "dexbot/basestrategy.py", line 361, in market_buy
  File "dexbot/basestrategy.py", line 499, in retry_action
  File "bitshares-0.1.16-py3.6.egg/bitshares/market.py", line 432, in buy
  File "bitshares-0.1.16-py3.6.egg/bitshares/bitshares.py", line 282, in finalizeOp
  File "bitshares-0.1.16-py3.6.egg/bitshares/transactionbuilder.py", line 388, in broadcast
  File "bitshares-0.1.16-py3.6.egg/bitshares/transactionbuilder.py", line 382, in broadcast
  File "graphenelib-0.6.2-py3.6.egg/grapheneapi/graphenewsrpc.py", line 214, in method
  File "bitshares-0.1.16-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: irrelevant signature included: Unnecessary signature(s) detected

## Specifications

  - Version:0.2.3
  - OS: OSX

**Comment by MarkoPaasila** [comment]
@alcafo it seems like you are running the BTS:USD market with an account for which uptick has several private keys. It just doesn't work with several private keys for an account, so what you need to do is remove one of them using `uptick removekey [privatekey]`, or wipe the wallet and start from scratch with `uptick wipewallet`.

**Comment by alcafo** [comment]
thanks @MarkoPaasila I was running two workers (one with his own private key), I updated to 0.2.4 (git pull) and all is working fine, you can close this issue, thanks again
