### ISSUE TITLE
staggered_orders  bug

### ISSUE THREAD

**Issue by hiquanta** [Codaone/DEXBot#152]
## Expected Behavior
When an order is filled, the order cannot be placed again

## Actual Behavior
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/er/.local/lib/python3.5/site-packages/SQLAlchemy-1.2.7-py3.5-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1808, in delete
    state = attributes.instance_state(instance)
AttributeError: 'NoneType' object has no attribute '_sa_instance_state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/er/.local/lib/python3.5/site-packages/dexbot-0.2.4-py3.5.egg/dexbot/storage.py", line 138, in run
    func(*args)
  File "/home/er/.local/lib/python3.5/site-packages/dexbot-0.2.4-py3.5.egg/dexbot/storage.py", line 259, in _remove_order
    self.session.delete(e)
  File "/home/er/.local/lib/python3.5/site-packages/SQLAlchemy-1.2.7-py3.5-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1810, in delete
    raise exc.UnmappedInstanceError(instance)
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version: 0.2.4
  - OS: linux

**Comment by MarkoPaasila** [comment]
Steps to reproduce: Start Staggered Orders strategy and wait for bug to occur :-)

**Comment by bitfag** [comment]
I can confirm this, very annoying bug.

**Comment by bitfag** [comment]
OK this happening because order removal happens twice:

```
2018-05-30 21:40:35,610 - xxxxworker2 using account xxx on BTS/USD - INFO - Change detected, updating orders
removing <dexbot.storage.Orders object at 0x7fe4f4d4bb38>
2018-05-30 21:40:35,724 - xxxxworker2 using account xxxx on BTS/USD - INFO - Placing a sell order for 10.0 BTS @ 0.18068988
removing None
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/SQLAlchemy-1.2.7-py3.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1808, in delete
    state = attributes.instance_state(instance)
AttributeError: 'NoneType' object has no attribute '_sa_instance_state'
```
