### ISSUE TITLE
USD does not exist error on worker start

### ISSUE THREAD

**Issue by grctest** [Codaone/DEXBot#159]
## Expected Behavior

USD worker runs

## Actual Behavior

Got an error when starting the USD worker

## Steps to Reproduce the Problem

  1. Run the USD worker
  2. Get the error
  3.

## Specifications

  - Version: 0.2.3
  - OS: Xubuntu

## Debug log:

```
Traceback (most recent call last):
  File "dexbot/views/errors.py", line 50, in func_wrapper
  File "dexbot/views/worker_item.py", line 60, in start_worker
  File "dexbot/controllers/main_controller.py", line 40, in create_worker
  File "dexbot/worker.py", line 170, in add_worker
  File "dexbot/worker.py", line 93, in update_notify
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/notify.py", line 118, in reset_subscriptions
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/notify.py", line 107, in get_market_ids
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/market.py", line 50, in __init__
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/asset.py", line 33, in __init__
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/blockchainobject.py", line 107, in __init__
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/asset.py", line 40, in refresh
bitshares.exceptions.AssetDoesNotExistsException: USD
```

**Comment by MarkoPaasila** [comment]
You need to read the pinned message in dexbot chat, see also troubleshooting in wiki. Cheers :-)

**Comment by mikakoi** [comment]
What node are you using for this?

**Comment by joelvai** [comment]
Is this still an active bug?

**Comment by bitfag** [comment]
There is probably no such bug now.
