### ISSUE TITLE
New release not running on Win 10 64

### ISSUE THREAD

**Issue by lsji07** [Codaone/DEXBot#168]
## Expected Behavior

Run GUI.

## Actual Behavior

GUI not launched. Following is the most recent error found.

Traceback (most recent call last):
  File "dexbot\gui.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\disturbedtk\projects\dexbot\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "bitshares\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\disturbedtk\projects\dexbot\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "bitshares\bitshares.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\disturbedtk\projects\dexbot\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "bitsharesbase\account.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\disturbedtk\projects\dexbot\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "graphenebase\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\disturbedtk\projects\dexbot\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "graphenebase\bip38.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\disturbedtk\projects\dexbot\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "scrypt\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\disturbedtk\projects\dexbot\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "scrypt\scrypt.py", line 15, in <module>
  File "ctypes\__init__.py", line 425, in LoadLibrary
  File "lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 151, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\LW\\AppData\\Local\\Temp\\_MEI38082\\_scrypt.pyd'. Most probably this dynlib/dll was not found when the application was frozen.
[7604] Failed to execute script gui
[7604] LOADER:

## Steps to Reproduce the Problem

  1. Open GUI,.exe latest release
  2. 
  3. Watch it shut.

## Specifications

  - Version: 0.2.5
  - OS: Windows 10 Pro 64

**Comment by MarkoPaasila** [comment]
This should be fixed with new binaries replacing the ones released.
