### ISSUE TITLE
Workers hanging with staggered orders

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#169]
## Actual Behavior

I run 3 workers on staggered orders simultaneously via cli. At the bot startup I see messages from all 3 workers. Later, I see log messages only from (2) worker despite there are filled orders on worker (1). Looks like there is a problem somewhere in workers notification system. I will try to investigate further.

## Specifications

  - Version: 0.2.7

**Comment by bitfag** [comment]
OK, there is an unhandled exception which causes disabled worker.

```
2018-06-02 03:23:18,479 (staggered_orders:258) - dh100-worker1 - DEBUG - tick-tack: dh100-worker1
2018-06-02 03:23:18,479 (staggered_orders:258) - dh100-worker2 - DEBUG - tick-tack: dh100-worker2
2018-06-02 03:23:18,479 (staggered_orders:258) - dh100-worker3 - DEBUG - tick-tack: dh100-worker3
2018-06-02 03:24:54,710 (basestrategy:358) - dh100-worker2 - INFO - Placing a buy order for 17.2798 USD @ 0.19086885
2018-06-02 03:24:58,679 (worker:141) - dh100-worker2 - ERROR - in onMarketUpdate()
Traceback (most recent call last):
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
    return self.rpc.rpcexec(self, payload)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/graphenelib-0.6.2-py3.6.egg/grapheneapi/graphenewsrpc.py", line 174, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: d.get_balance( *_seller, *_sell_asset ) >= op.amount_to_sell: insufficient balance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vvk/devel/DEXBot/dexbot/worker.py", line 139, in on_market
    self.workers[worker_name].onMarketUpdate(data)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/vvk/devel/DEXBot/dexbot/strategies/staggered_orders.py", line 160, in check_orders
    self.place_reverse_order(order)
  File "/home/vvk/devel/DEXBot/dexbot/strategies/staggered_orders.py", line 121, in place_reverse_order
    new_order = self.market_buy(amount, price)
  File "/home/vvk/devel/DEXBot/dexbot/basestrategy.py", line 367, in market_buy
    returnOrderId="head"
  File "/home/vvk/devel/DEXBot/dexbot/basestrategy.py", line 505, in retry_action
    return action(*args, **kwargs)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/market.py", line 432, in buy
    tx = self.blockchain.finalizeOp(order, account["name"], "active", **kwargs)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/bitshares.py", line 282, in finalizeOp
    return self.txbuffer.broadcast()
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/transactionbuilder.py", line 388, in broadcast
    raise e
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/transactionbuilder.py", line 382, in broadcast
    ret, api="network_broadcast")
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/graphenelib-0.6.2-py3.6.egg/grapheneapi/graphenewsrpc.py", line 214, in method
    r = self.rpcexec(query)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 66, in rpcexec
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: d.get_balance( *_seller, *_sell_asset ) >= op.amount_to_sell: insufficient balance
2018-06-02 03:24:58,779 (worker:135) - dh100-worker2 - DEBUG - Worker "dh100-worker2" is disabled
```

**Comment by bitfag** [comment]
Looks like there is 2 different bugs:

1. Hanging workers
2. Unexpected insufficient balance

**Comment by MarkoPaasila** [comment]
The insufficient balance is likely a consequence of the maintenance strategy not working properly: canceling orders at exit and replacing them assuming that center price is still the same and the confusion following from orders being filled while replacing all orders.

**Comment by bitfag** [comment]
No, there was no orders cancelling at exit (this version don't cancel orders), it's something other happening which needs to be debugged.

**Comment by bitfag** [comment]
OK I tracked down this issue to the roots.

The problem is on **overall bad design in handling market updates**. Every worker adds a subscription to the bitshares market via `bitshares.Notify()`. On every market update you're getting an event in `on_market()` callback inside worker.py which leads to calling `self.workers[worker_name].onMarketUpdate(data)` which then calls `Strategy.check_orders()`. With staggered orders this leads to **querying bitshares for each placed order every time market update comes** which may take 3-4 seconds!!!

On active market there are lots of market changes constantly, so bot parses new notifications too slow! He just always stays beyond the actual market. In the active markets like BTS/USD there are lots of orders happening, but the bot is able to parse only one in 3-4 seconds (depending on number of orders and lag to the node).

This is an example time measurements how the bot is working:
```
2018-06-03 10:59:06,992 - dexbot.worker - INFO - got callback on market: {'base': <Asset 1.3.0>, 'quote': <Asset 1.3.121>}, 21.5237 USD 99.00243 BTS @ 4.599693826 BTS/USD
2018-06-03 10:59:06,993 - dexbot.worker - INFO - lock acquired, time: 0:00:00.000005
2018-06-03 10:59:06,993 - dexbot.worker - INFO - got market update on worker market: BTS/USD
2018-06-03 10:59:13,081 - dexbot.worker - INFO - time spent inside: 0:00:06.088703
2018-06-03 10:59:13,082 - dexbot.worker - INFO - on_market execution took: 0:00:06.089042
```
