### ISSUE TITLE
Connection Errors

### ISSUE THREAD

**Issue by lsji07** [Codaone/DEXBot#178]
## Expected Behavior

Run GUI with minimal errors

## Actual Behavior

Several connection errors found after running over night.

Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "threading.py", line 862, in run
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\websocket.py", line 216, in _ping
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\websocket.py", line 388, in method
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\websocket.py", line 354, in rpcexec
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_app.py", line 147, in send
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_core.py", line 240, in send
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_core.py", line 265, in send_frame
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_core.py", line 430, in _send
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_socket.py", line 117, in send
  File "ssl.py", line 869, in send
  File "ssl.py", line 594, in write
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

[WinError 10054] An existing connection was forcibly closed by the remote host
Traceback (most recent call last):
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_app.py", line 278, in run_forever
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_app.py", line 63, in read
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_app.py", line 251, in read
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_core.py", line 330, in recv_data_frame
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_core.py", line 364, in recv_frame
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_abnf.py", line 361, in recv_frame
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_abnf.py", line 309, in recv_header
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_abnf.py", line 396, in recv_strict
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_core.py", line 434, in _recv
  File "lib\site-packages\websocket_client-0.47.0-py3.5.egg\websocket\_socket.py", line 81, in recv
  File "ssl.py", line 922, in recv
  File "ssl.py", line 799, in read
  File "ssl.py", line 585, in read
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
close status: 31522

## Specifications

  - Version: 0.3.0 with latest binaries as latest release. Like the new GUI btw.....
  - OS: Win Pro 64

**Comment by MarkoPaasila** [comment]
This isn't an error of DEXBot itself, but a problem we must circumvent somehow. I created an issue #192  for discussing automatic node switching, which would mitigate the issue. I'll close this issue and we can continue in #192
