### ISSUE TITLE
[Error initializing Bot]

### ISSUE THREAD

**Issue by Gomes90** [Codaone/DEXBot#188]
## Expected Behavior
Worker Running and Orders Placed

## Actual Behavior
Upon Starting the bot gives an error 'Worker Initialization' (See file attached)

Log:

Traceback (most recent call last):
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 54, in rpcexec
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: irrelevant signature included: Unnecessary signature(s) detected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot\worker.py", line 75, in init_workers
  File "dexbot\strategies\relative_orders.py", line 40, in __init__
  File "dexbot\strategies\relative_orders.py", line 130, in check_orders
  File "dexbot\strategies\relative_orders.py", line 101, in update_orders
  File "dexbot\basestrategy.py", line 375, in market_buy
  File "dexbot\basestrategy.py", line 513, in retry_action
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\market.py", line 432, in buy
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\bitshares.py", line 282, in finalizeOp
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\transactionbuilder.py", line 388, in broadcast
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\transactionbuilder.py", line 382, in broadcast
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 213, in method
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: irrelevant signature included: Unnecessary signature(s) detected

## Steps to Reproduce the Problem

Please see configuration in file attached-

## Specifications

  - Version: 0.3.0
  - OS: Windows

![screenshot_4](https://user-images.githubusercontent.com/38591101/41070849-e519eeb8-69ec-11e8-9abd-de3d2b7782b2.png)
![screenshot_3](https://user-images.githubusercontent.com/38591101/41070850-e5332f72-69ec-11e8-93dd-c493a7ecdd28.png)

**Comment by MarkoPaasila** [comment]
See common problems in wiki
