### ISSUE TITLE
Worker initialisation

### ISSUE THREAD

**Issue by ckerflag** [Codaone/DEXBot#211]
Traceback (most recent call last)      **How do I fix this???**
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 54, in rpcexec
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: irrelevant signature included: Unnecessary signature(s) detected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot\worker.py", line 76, in init_workers
  File "dexbot\strategies\relative_orders.py", line 60, in __init__
  File "dexbot\strategies\relative_orders.py", line 149, in check_orders
  File "dexbot\strategies\relative_orders.py", line 124, in update_orders
  File "dexbot\basestrategy.py", line 436, in market_buy
  File "dexbot\basestrategy.py", line 580, in retry_action
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\market.py", line 432, in buy
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\bitshares.py", line 282, in finalizeOp
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\transactionbuilder.py", line 388, in broadcast
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\transactionbuilder.py", line 382, in broadcast
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 213, in method
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: irrelevant signature included: Unnecessary signature(s) detected

**Comment by ckerflag** [comment]
Anyone out there can you help me???????

**Comment by mikakoi** [comment]
You have multiple private keys for the same account on dexbot. If you had used the bug report template I'd know what platform you're using and I'd be able to tell you which file to delete to fix this issue.

**Comment by ckerflag** [comment]
I am on bitshares compumatrix my user account is hope-1 I added rescue-1 and both were working and then it stopped and I deleted and re-installed and when that did not work I created a hope-2 account but that did work either so I am back to hope-1 and it opens with my password but just get that error message.

**Comment by ckerflag** [comment]
I would like to get them both up and running again hope-1 and rescue-1

**Comment by mikakoi** [comment]
I meant what is your OS? Mac, Win or Linux?

**Comment by ckerflag** [comment]
Windows 8.1

**Comment by mikakoi** [comment]
You need to remove this file: 
`C:\Users<user>\AppData\Local\Fabian Schuh\bitshares\bitshares.sqlite`

**Comment by ckerflag** [comment]
How do you go about that? just getting started here I need instructions

**Comment by mikakoi** [comment]
What do you mean, just remove the file and it will fix this issue

**Comment by ckerflag** [comment]
It is there with but when I right click it won't delete when I try to open it error message it can not be found

**Comment by mikakoi** [comment]
I'm sorry but I can't help you with Windows related issues. I told you what you need to do to fix this issue.
I'm closing this issue.
