### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ckerflag** [Codaone/DEXBot#215]
## Expected Behavior 
start botup

## Actual Behavior
Assert Exception

## Steps to Reproduce the Problem

  1.start bot
  2.Assert Exception
  3.same

## Specifications  dexbot-gui 64 link

  - Version: 0.4.6
  - OS:  windows 8.1
Traceback (most recent call last):
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 54, in rpcexec
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: now <= trx.expiration: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot\worker.py", line 76, in init_workers
  File "dexbot\strategies\relative_orders.py", line 60, in __init__
  File "dexbot\strategies\relative_orders.py", line 149, in check_orders
  File "dexbot\strategies\relative_orders.py", line 124, in update_orders
  File "dexbot\basestrategy.py", line 436, in market_buy
  File "dexbot\basestrategy.py", line 580, in retry_action
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\market.py", line 432, in buy
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\bitshares.py", line 282, in finalizeOp
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\transactionbuilder.py", line 388, in broadcast
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\transactionbuilder.py", line 382, in broadcast
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 213, in method
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: now <= trx.expiration:

**Comment by ckerflag** [comment]
Can you help me?

**Comment by mikakoi** [comment]
The error means that your transaction expired, there isn't much I can do to help. You can try it again, these kind of errors happen seldom.
