### ISSUE TITLE
error when trying to add worker

### ISSUE THREAD

**Issue by hubba1** [Codaone/DEXBot#217]
## Expected Behavior
expected it to add worker....I downloaded the new version and tried to add worker and this is what I got...

## Actual Behavior
Traceback (most recent call last):
File "dexbot\views\errors.py", line 95, in func_wrapper
File "dexbot\controllers\worker_controller.py", line 206, in validate_form
File "dexbot\controllers\worker_controller.py", line 181, in validate_account
File "dexbot\controllers\worker_controller.py", line 80, in is_account_valid
File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesbase\account.py", line 151, in __init__
File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\graphenebase\account.py", line 311, in __init__
File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\graphenebase\base58.py", line 51, in __init__
File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\graphenebase\base58.py", line 180, in base58CheckDecode
AssertionError

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - OS:

**Comment by MarkoPaasila** [comment]
See common errors in wiki

**Comment by kohako** [comment]
I have an assertion error as well and cant work it out ? I have checked the wiki errors.
