### ISSUE TITLE
Assert Exception 

### ISSUE THREAD

**Issue by ckerflag** [Codaone/DEXBot#219]
## Steps to Reproduce the Problem

  1.start bot 
  2.assert exception 
  3.same

## Specifications  

  - Version: 0.4.6  dexbot-gui 64 
  - OS: windows 8.1 
Traceback (most recent call last):
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 54, in rpcexec
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: now <= trx.expiration: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot\worker.py", line 76, in init_workers
  File "dexbot\strategies\relative_orders.py", line 60, in __init__
  File "dexbot\strategies\relative_orders.py", line 149, in check_orders
  File "dexbot\strategies\relative_orders.py", line 124, in update_orders
  File "dexbot\basestrategy.py", line 436, in market_buy
  File "dexbot\basestrategy.py", line 580, in retry_action
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\market.py", line 432, in buy
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\bitshares.py", line 282, in finalizeOp
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\transactionbuilder.py", line 388, in broadcast
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\transactionbuilder.py", line 382, in broadcast
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 213, in method
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: now <= trx.expiration:

Should I just uninstall and re-install to fix this issue?

**Comment by ckerflag** [comment]
I deleted the bot and ran a search and deleted all files re-installed 0.4.8 and I am still getting assert exception.

**Comment by ckerflag** [comment]
OMG I fixed it!!!!!!!   you will never believe what it was....... I have put major labor into fixing my bot I even reset google chrome completely and cleaned everything out and it still was assert exception I hate those words and then today the Dex would not come up and told me to resynchronize  my clock on my pc so I did and man did that ever work good no lag at all soooooo I thought I bet my bot will work now and shazzammm and turned right on and took off and I did a happy dance ......lol  :grinning: :sun_with_face: :man_dancing: :man_dancing:
