### ISSUE TITLE
AssertionError() when trying to create a worker

### ISSUE THREAD

**Issue by edwinux** [Codaone/DEXBot#227]
## Expected Behavior
Trying to create a new worker

## Actual Behavior
Get an error message "An error occurred with DEXBot: AssertionError()"
In the details:
"
 Traceback (most recent call last):
  File "dexbot\views\errors.py", line 95, in func_wrapper
  File "dexbot\controllers\worker_controller.py", line 206, in validate_form
  File "dexbot\controllers\worker_controller.py", line 181, in validate_account
  File "dexbot\controllers\worker_controller.py", line 80, in is_account_valid
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesbase\account.py", line 151, in __init__
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\graphenebase\account.py", line 311, in __init__
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\graphenebase\base58.py", line 53, in __init__
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\graphenebase\base58.py", line 180, in base58CheckDecode
AssertionError
"

## Specifications

  - Version: 0.4.8
  - OS: WIN 10 + UBUNTU 16.4, My clock is set to automatic and is synced.

Please help.

**Comment by MarkoPaasila** [comment]
See [Common Problems](https://github.com/Codaone/DEXBot/wiki/Common-problems) in the wiki.
