### ISSUE TITLE
[Windows] trx.expiration problem

### ISSUE THREAD

**Issue by Rolokmn** [Codaone/DEXBot#250]
## Expected Behavior

That the worker picks up correctly and does his job

## Actual Behavior (I get this error)

Traceback (most recent call last):
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 54, in rpcexec
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: trx.expiration <= now + chain_parameters.maximum_time_until_expiration: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot\worker.py", line 76, in init_workers
  File "dexbot\strategies\relative_orders.py", line 60, in __init__
  File "dexbot\strategies\relative_orders.py", line 149, in check_orders
  File "dexbot\strategies\relative_orders.py", line 124, in update_orders
  File "dexbot\basestrategy.py", line 436, in market_buy
  File "dexbot\basestrategy.py", line 580, in retry_action
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\market.py", line 432, in buy
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\bitshares.py", line 282, in finalizeOp
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\transactionbuilder.py", line 388, in broadcast
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\transactionbuilder.py", line 382, in broadcast
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 213, in method
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: trx.expiration <= now + chain_parameters.maximum_time_until_expiration:

## Steps to Reproduce the Problem

  1. Launch DEXBot-gui.exe
  2. Configure 1 worker
  3. Start worker

## Specifications

  - Version: 0.4.8
  - OS: Windows 10

**Comment by MarkoPaasila** [comment]
This seems to be a common problem on Windows, but not Linux. I have never had this running on Linux and a local node.

**Comment by 1nt3GraC2** [comment]
Here is screen of terminal window,  version 0.5.2 

![noworker](https://user-images.githubusercontent.com/41024293/43409239-af0401ea-9423-11e8-8781-4830f72430c8.png)

and traceback

Traceback (most recent call last):
  File "lib\site-packages\graphenelib-0.6.3-py3.5.egg\grapheneapi\api.py", line 127, in func
  File "lib\site-packages\graphenelib-0.6.3-py3.5.egg\grapheneapi\rpc.py", line 93, in method
  File "lib\site-packages\graphenelib-0.6.3-py3.5.egg\grapheneapi\rpc.py", line 63, in parse_response
grapheneapi.exceptions.RPCError: Assert Exception: trx.expiration <= now + chain_parameters.maximum_time_until_expiration: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot\worker.py", line 76, in init_workers
  File "dexbot\strategies\relative_orders.py", line 61, in __init__
  File "dexbot\strategies\relative_orders.py", line 150, in check_orders
  File "dexbot\strategies\relative_orders.py", line 125, in update_orders
  File "dexbot\basestrategy.py", line 440, in market_buy
  File "dexbot\basestrategy.py", line 584, in retry_action
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\market.py", line 432, in buy
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\bitshares.py", line 275, in finalizeOp
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\transactionbuilder.py", line 398, in broadcast
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\transactionbuilder.py", line 392, in broadcast
  File "lib\site-packages\graphenelib-0.6.3-py3.5.egg\grapheneapi\api.py", line 135, in func
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 19, in post_process_exception
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: trx.expiration <= now + chain_parameters.maximum_time_until_expiration:

**Comment by MarkoPaasila** [comment]
@1nt3GraC2 would you manage to install dexbot from source in windows and see if it does the same?

https://github.com/Codaone/DEXBot/wiki/Setup-Guide-for-Windows

**Comment by MarkoPaasila** [comment]
https://github.com/bitshares/python-bitshares/issues/122

**Comment by MarkoPaasila** [comment]
This is affecting many users, so I raised priority to high.

**Comment by 1nt3GraC2** [comment]
@MarkoPaasila sorry for my lameness, I cannot go through the setup guide,
 but I download new version 0.5.6 and have another traceback 
 
Traceback (most recent call last):
  File "lib\site-packages\grapheneapi\api.py", line 137, in func
  File "lib\site-packages\grapheneapi\rpc.py", line 93, in method
  File "lib\site-packages\grapheneapi\rpc.py", line 63, in parse_response
grapheneapi.exceptions.RPCError: Bad Cast: Invalid cast from type 'object_type' to Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot\worker.py", line 76, in init_workers
  File "dexbot\strategies\relative_orders.py", line 61, in __init__
  File "dexbot\strategies\relative_orders.py", line 150, in check_orders
  File "dexbot\strategies\relative_orders.py", line 125, in update_orders
  File "dexbot\basestrategy.py", line 457, in market_buy
  File "dexbot\basestrategy.py", line 602, in retry_action
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\market.py", line 432, in buy
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\bitshares.py", line 274, in finalizeOp
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\transactionbuilder.py", line 325, in sign
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\transactionbuilder.py", line 301, in constructTx
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitsharesbase\transactions.py", line 26, in addRequiredFees
  File "lib\site-packages\grapheneapi\api.py", line 145, in func
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 19, in post_process_exception
bitsharesapi.exceptions.UnhandledRPCError: Bad Cast: Invalid cast from type 'object_type' to Object

and same terminal screen

![noworker_3](https://user-images.githubusercontent.com/41024293/43668810-342463d4-977f-11e8-9bdc-617150210b32.png)

**Comment by MarkoPaasila** [comment]
Related to #263

**Comment by bitfag** [comment]
@Rolokmn do you able to reproduce the problem? Which bitshares nodes you are using? Do you have time set correctly on the your machine? Is it NTP-synced?

As I understand, the possible reasons are:
* The time on the local machine is wrong so trx.expiration is not fit to limits
* Bitshares node out of sync

**Comment by MarkoPaasila** [comment]
This is transaction expiration time, is it? Not related to order expiration time. Could this be handled by retrying with a longer expiration time?

**Comment by bitfag** [comment]
The problem is specified transaction expiration time was not fit into bounds (which is "time of the current head block + 1 day"). This means expiration was set beyond the current time or too much in the feature. Causes?

* Client's machine datetime is shifted too much away from current time
* Bitshares node not synced and it's "now" is in the past

Basically, there is nothing to do with dexbot. The only thing dexbot can do it to check for these conditions.

1. Obtain current time from the NTP server
2. Compare machine time with NTP
3. Compare chain head block time with NTP
4. Give a meaningful warning message to the user

**Comment by MarkoPaasila** [comment]
Could we automatically switch node if this happens?

**Comment by bitfag** [comment]
Probably yes, but I think just retry should be enough, also user may have only one node in the config.

**Comment by 1nt3GraC2** [comment]
@MarkoPaasila Sorry, my bad, thank you for link

@bitfag Yes, all of two computers :D with same issue is NTP synced, more than two times in past week. And before sync and after sync was the same.

@all thank you, with 0.5.10 release I've got many exceptions in terminal window, but the bot is running and working. 
![exceptions](https://user-images.githubusercontent.com/41024293/44222268-49295280-a184-11e8-9a71-da3303c2342d.png)

**Comment by MarkoPaasila** [comment]
xeroc promised to look into this time issue with pybitshares.

**Comment by MarkoPaasila** [comment]
https://github.com/bitshares/python-bitshares/issues/155

**Comment by dominic22** [comment]
I think this issue can be closed, since the following PR fixes it according to:
https://github.com/Codaone/DEXBot/pull/488
