### ISSUE TITLE
[0.5.6] Bad Cast: Invalid cast from type 'object_type' to Object

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#263]
100% reproducible, worker cannot place orders, critical bug.

```
2018-08-06 12:43:32,280 - dtest1 using account dtest1 on GOLODRANETS/TEST - INFO - Initializing Staggered Sell
2018-08-06 12:43:32,366 - dtest1 using account dtest1 on GOLODRANETS/TEST - INFO - Canceling all orders
2018-08-06 12:43:32,538 - dtest1 using account dtest1 on GOLODRANETS/TEST - INFO - Orders canceled
2018-08-06 12:43:35,141 - dtest1 using account dtest1 on GOLODRANETS/TEST - INFO - Placing a sell order for 534.7186 GOLODRANETS @ 1.05356538
2018-08-06 12:43:36,016 - dtest1 using account dtest1 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/grapheneapi/api.py", line 137, in func
    r = func(*args, **kwargs)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/grapheneapi/rpc.py", line 93, in method
    message = self.parse_response(r)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/grapheneapi/rpc.py", line 63, in parse_response
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Bad Cast: Invalid cast from type 'object_type' to Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vvk/devel/DEXBot/dexbot/worker.py", line 76, in init_workers
    view=self.view
  File "/home/vvk/devel/DEXBot/dexbot/strategies/staggered_sell.py", line 91, in __init__
    self.update_orders()
  File "/home/vvk/devel/DEXBot/dexbot/strategies/staggered_sell.py", line 352, in update_orders
    order = self.market_sell(self.amount, sell_prices[i], expiration=self.expiration)
  File "/home/vvk/devel/DEXBot/dexbot/basestrategy.py", line 509, in market_sell
    **kwargs
  File "/home/vvk/devel/DEXBot/dexbot/basestrategy.py", line 614, in retry_action
    return action(*args, **kwargs)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.19-py3.6.egg/bitshares/market.py", line 510, in sell
    tx = self.blockchain.finalizeOp(order, account["name"], "active", **kwargs)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.19-py3.6.egg/bitshares/bitshares.py", line 274, in finalizeOp
    self.txbuffer.sign()
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.19-py3.6.egg/bitshares/transactionbuilder.py", line 325, in sign
    self.constructTx()
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.19-py3.6.egg/bitshares/transactionbuilder.py", line 301, in constructTx
    asset_id=self.fee_asset_id)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.19-py3.6.egg/bitsharesbase/transactions.py", line 26, in addRequiredFees
    fees = ws.get_required_fees([i.json() for i in ops], asset_id)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/grapheneapi/api.py", line 145, in func
    self.post_process_exception(e)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.19-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 19, in post_process_exception
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Bad Cast: Invalid cast from type 'object_type' to Object
2018-08-06 12:43:36,020 - dexbot.worker - CRITICAL - No workers actually running
```

**Comment by mikakoi** [comment]
It seems like the culprit here is the fee_asset in the transaction. I tested the feature on friday and it worked just fine, not sure why it isn't working. Fix for this is to remove fee asset option for now and make an issue to py-bitshares repo.

**Comment by bitfag** [comment]
This is an error in python-bitshares, I already tested a fix and will push it soon.

**Comment by bitfag** [comment]
Actually python-bitshares don't expect `Asset` as argument for `fee_asset`, it expects Amount or plain asset id as '1.3.0' (str), so this can be quickly fixed in the dexbot side.
