### ISSUE TITLE
Assert Exception: min_to_receive.amount > 0

### ISSUE THREAD

**Issue by Cobb-Chang** [Codaone/DEXBot#276]
## Expected Behavior
the DEXBot work normally in some assert, but not work well in btc_ltc trade.

## Actual Behavior
error

## Steps to Reproduce the Problem

account: cobb-chang-bot2
      amount: 30.0
      center_price: 0.0
      center_price_dynamic: true
      center_price_offset: false
      fee_asset: CYB
      manual_offset: 0.0
      market: JADE.BTC/JADE.LTC
      module: dexbot.strategies.relative_orders
      relative_order_size: true
      spread: 0.5

## Specifications

  - Version:
  - OS:

2018-08-16 13:48:23,156 - btc_ltc using account cobb-chang-bot2 on JADE.BTC/JADE.LTC - INFO - Initializing Relative Orders
2018-08-16 13:48:23,173 - btc_ltc using account cobb-chang-bot2 on JADE.BTC/JADE.LTC - INFO - Change detected, updating orders
2018-08-16 13:48:23,646 - btc_ltc using account cobb-chang-bot2 on JADE.BTC/JADE.LTC - INFO - Canceling all orders
2018-08-16 13:48:23,728 - btc_ltc using account cobb-chang-bot2 on JADE.BTC/JADE.LTC - INFO - Orders canceled
2018-08-16 13:48:23,808 - btc_ltc using account cobb-chang-bot2 on JADE.BTC/JADE.LTC - INFO - Placing a buy order for 0.0178266 JADE.LTC @ -94.68744366
2018-08-16 13:48:30,432 - btc_ltc using account cobb-chang-bot2 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\graphenelib-0.6.6-py3.6.egg\grapheneapi\api.py", line 137, in func
    r = func(*args, **kwargs)
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\graphenelib-0.6.6-py3.6.egg\grapheneapi\rpc.py", line 93, in method
    message = self.parse_response(r)
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\graphenelib-0.6.6-py3.6.egg\grapheneapi\rpc.py", line 63, in parse_response
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: min_to_receive.amount > 0: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\File\work file\bitshare\DEXBot-0.5.10\dexbot\worker.py", line 76, in init_workers
    view=self.view
  File "D:\File\work file\bitshare\DEXBot-0.5.10\dexbot\strategies\relative_orders.py", line 68, in __init__
    self.check_orders()
  File "D:\File\work file\bitshare\DEXBot-0.5.10\dexbot\strategies\relative_orders.py", line 219, in check_orders
    self.update_orders()
  File "D:\File\work file\bitshare\DEXBot-0.5.10\dexbot\strategies\relative_orders.py", line 192, in update_orders
    buy_order = self.market_buy(amount_base, self.buy_price, True)
  File "D:\File\work file\bitshare\DEXBot-0.5.10\dexbot\basestrategy.py", line 463, in market_buy
    **kwargs
  File "D:\File\work file\bitshare\DEXBot-0.5.10\dexbot\basestrategy.py", line 614, in retry_action
    return action(*args, **kwargs)
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\bitshares-0.1.19-py3.6.egg\bitshares\market.py", line 432, in buy
    tx = self.blockchain.finalizeOp(order, account["name"], "active", **kwargs)
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\bitshares-0.1.19-py3.6.egg\bitshares\bitshares.py", line 275, in finalizeOp
    return self.txbuffer.broadcast()
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\bitshares-0.1.19-py3.6.egg\bitshares\transactionbuilder.py", line 398, in broadcast
    raise e
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\bitshares-0.1.19-py3.6.egg\bitshares\transactionbuilder.py", line 392, in broadcast
    ret, api="network_broadcast")
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\graphenelib-0.6.6-py3.6.egg\grapheneapi\api.py", line 145, in func
    self.post_process_exception(e)
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\bitshares-0.1.19-py3.6.egg\bitsharesapi\bitsharesnoderpc.py", line 19, in post_process_exception
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: min_to_receive.amount > 0:

**Comment by bitfag** [comment]
> Placing a buy order for 0.0178266 JADE.LTC @ -94.68744366

Negative price, because of `center_price: 0.0`. Probably strategy should not allow `canter_price = 0`. @MarkoPaasila ?

**Comment by bitfag** [comment]
Oops, there is `center_price_dynamic: true`, so it definetely from the market. Probably the bug is somewhere else because price should not be negative. Need a testcase to reproduce.

**Comment by MarkoPaasila** [comment]
This looks like it makes center price negative when calculating from market orders. Could it be that some price is inverse at the time of calculating center?

**Comment by Cobb-Chang** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\File\work file\bitshare\DEXBot-0.5.10 - 20180816-21-23\dexbot\worker.py", line 142, in on_market
    self.workers[worker_name].onMarketUpdate(data)
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\events\events.py", line 95, in __call__
    f(*a, **kw)
  File "D:\File\work file\bitshare\DEXBot-0.5.10 - 20180816-21-23\dexbot\strategies\relative_orders.py", line 247, in check_orders
    self.update_orders()
  File "D:\File\work file\bitshare\DEXBot-0.5.10 - 20180816-21-23\dexbot\strategies\relative_orders.py", line 221, in update_orders
    self.update_orders()
  File "D:\File\work file\bitshare\DEXBot-0.5.10 - 20180816-21-23\dexbot\strategies\relative_orders.py", line 221, in update_orders
    self.update_orders()
  File "D:\File\work file\bitshare\DEXBot-0.5.10 - 20180816-21-23\dexbot\strategies\relative_orders.py", line 221, in update_orders
    self.update_orders()
  [Previous line repeated 5 more times]
  File "D:\File\work file\bitshare\DEXBot-0.5.10 - 20180816-21-23\dexbot\strategies\relative_orders.py", line 209, in update_orders
    sell_order = self.market_sell(amount_quote, self.sell_price, True)
  File "D:\File\work file\bitshare\DEXBot-0.5.10 - 20180816-21-23\dexbot\basestrategy.py", line 509, in market_sell
    **kwargs
  File "D:\File\work file\bitshare\DEXBot-0.5.10 - 20180816-21-23\dexbot\basestrategy.py", line 614, in retry_action
    return action(*args, **kwargs)
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\bitshares-0.1.19-py3.6.egg\bitshares\market.py", line 510, in sell
    tx = self.blockchain.finalizeOp(order, account["name"], "active", **kwargs)
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\bitshares-0.1.19-py3.6.egg\bitshares\bitshares.py", line 275, in finalizeOp
    return self.txbuffer.broadcast()
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\bitshares-0.1.19-py3.6.egg\bitshares\transactionbuilder.py", line 398, in broadcast
    raise e
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\bitshares-0.1.19-py3.6.egg\bitshares\transactionbuilder.py", line 392, in broadcast
    ret, api="network_broadcast")
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\graphenelib-0.6.6-py3.6.egg\grapheneapi\api.py", line 145, in func
    self.post_process_exception(e)
  File "C:\Users\potat\AppData\Local\Programs\Python\Python36\lib\site-packages\bitshares-0.1.19-py3.6.egg\bitsharesapi\bitsharesnoderpc.py", line 19, in post_process_exception
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: min_to_receive.amount > 0:

**Comment by joelvai** [comment]
@Cobb-Chang have you tried that latest version of DEXBot? If this is still on going problem, let me know.

**Comment by MarkoPaasila** [comment]
It seems like this is something inside pybitshares. Someone got this same error from using it directly.

**Comment by joelvai** [comment]
Wonder if bitshares 0.2.0 fixed this. I try to reproduce it.
