### ISSUE TITLE
unable to cancel order

### ISSUE THREAD

**Issue by Cobb-Chang** [Codaone/DEXBot#334]
Traceback (most recent call last):
  File "D:\software\Python\Python36\lib\site-packages\graphenelib-0.6.6-py3.6.egg\grapheneapi\api.py", line 137, in func
    r = func(*args, **kwargs)
  File "D:\software\Python\Python36\lib\site-packages\graphenelib-0.6.6-py3.6.egg\grapheneapi\rpc.py", line 93, in method
    message = self.parse_response(r)
  File "D:\software\Python\Python36\lib\site-packages\graphenelib-0.6.6-py3.6.egg\grapheneapi\rpc.py", line 63, in parse_response
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: trx.operations.size() == 1: A trade related transaction cannot have more than one operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\dexbot\DEXBot-0.7.1\dexbot\strategies\base.py", line 256, in _cancel_orders
    orders, account=self.account, fee_asset=self.fee_asset['id']
  File "E:\dexbot\DEXBot-0.7.1\dexbot\strategies\base.py", line 1009, in retry_action
    return action(*args, **kwargs)
  File "D:\software\Python\Python36\lib\site-packages\bitshares-0.1.22-py3.6.egg\bitshares\bitshares.py", line 1243, in cancel
    return self.finalizeOp(op, account["name"], "active", **kwargs)
  File "D:\software\Python\Python36\lib\site-packages\bitshares-0.1.22-py3.6.egg\bitshares\bitshares.py", line 276, in finalizeOp
    return self.txbuffer.broadcast()
  File "D:\software\Python\Python36\lib\site-packages\bitshares-0.1.22-py3.6.egg\bitshares\transactionbuilder.py", line 423, in broadcast
    raise e
  File "D:\software\Python\Python36\lib\site-packages\bitshares-0.1.22-py3.6.egg\bitshares\transactionbuilder.py", line 421, in broadcast
    ret, api="network_broadcast")
  File "D:\software\Python\Python36\lib\site-packages\graphenelib-0.6.6-py3.6.egg\grapheneapi\api.py", line 145, in func
    self.post_process_exception(e)
  File "D:\software\Python\Python36\lib\site-packages\bitshares-0.1.22-py3.6.egg\bitsharesapi\bitsharesnoderpc.py", line 19, in post_process_exception
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: trx.operations.size() == 1: A trade related transaction cannot have more than one operation

**Comment by joelvai** [comment]
Can you provide more information such as OS, Version, Strategy, at what point did this happen?

**Comment by Cobb-Chang** [comment]
> Can you provide more information such as OS, Version, Strategy, at what point did this happen?

i think change the code : dexbot/base.py  cancel_orders
 from:
           orders = [order['id'] for order in orders if 'id' in order]
           success = self._cancel_orders(orders)
to:
           orders = [order['id'] for order in orders if 'id' in order]
           for ordersID in orders:
                success = self._cancel_orders(ordersID )

can fix this problem

**Comment by Cobb-Chang** [comment]
> Can you provide more information such as OS, Version, Strategy, at what point did this happen?

lost one "return False" in the function _cancel_orders

**Comment by MarkoPaasila** [comment]
Thanks @Cobb-Chang. https://github.com/Codaone/DEXBot/pull/336

**Comment by Cobb-Chang** [comment]
> > Thanks @Cobb-Chang. #336
> 
> ```
> def _cancel_orders(self, orders):
>     """
> 
>         :param orders:
>         :return:
>     """
>     # Todo: Add documentation
>     try:
>         self.retry_action(
>             self.bitshares.cancel,
>             orders, account=self.account, fee_asset=self.fee_asset['id']
>         )
>     except bitsharesapi.exceptions.UnhandledRPCError as exception:
>         if str(exception).startswith('Assert Exception: maybe_found != nullptr: Unable to find Object'):
>             # The order(s) we tried to cancel doesn't exist
>             self.bitshares.txbuffer.clear()
>             return False
>         else:
>             #self.log.exception("Unable to cancel order")
>             return False
>     except bitshares.exceptions.MissingKeyError:
>         self.log.exception('Unable to cancel order(s), private key missing.')
>         return False
> 
>     return True
> ```
> delete the "self.log.exception("Unable to cancel order")". Or it will report error all the time

@joelvai

**Comment by joelvai** [comment]
I will look into it, thanks for pointing out.
