### ISSUE TITLE
in ontick()

### ISSUE THREAD

**Issue by shef4ig** [Codaone/DEXBot#340]
## Actual Behavior
Traceback (most recent call last):
  File "lib\site-packages\grapheneapi\api.py", line 137, in func
  File "lib\site-packages\grapheneapi\rpc.py", line 93, in method
  File "lib\site-packages\grapheneapi\rpc.py", line 63, in parse_response
grapheneapi.exceptions.RPCError: Assert Exception: now <= trx.expiration: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot\worker.py", line 122, in on_block
  File "lib\site-packages\events-0.3-py3.5.egg\events\events.py", line 95, in __call__
  File "dexbot\strategies\staggered_orders.py", line 1134, in tick
  File "dexbot\strategies\staggered_orders.py", line 221, in maintain_strategy
  File "dexbot\basestrategy.py", line 485, in execute
  File "lib\site-packages\bitshares-0.1.22-py3.5.egg\bitshares\transactionbuilder.py", line 423, in broadcast
  File "lib\site-packages\bitshares-0.1.22-py3.5.egg\bitshares\transactionbuilder.py", line 417, in broadcast
  File "lib\site-packages\grapheneapi\api.py", line 145, in func
  File "lib\site-packages\bitshares-0.1.22-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 19, in post_process_exception
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: now <= trx.expiration:
http://prntscr.com/l411ug
## Steps to Reproduce the Problem

  1. http://prntscr.com/l41238
  2. Start http://prntscr.com/l412ah
  3. http://prntscr.com/l411ug

## Specifications

  - Version: 0.7.1
  - OS:win 64

**Comment by shef4ig** [comment]
помогло, спасибо

вт, 9 окт. 2018 г. в 21:25, Marko Paasila <notifications@github.com>:

**Comment by MarkoPaasila** [comment]
Did you try changing the node?

**Comment by shef4ig** [comment]
working, i am syncing windows time.

ср, 10 окт. 2018 г. в 9:59, Marko Paasila <notifications@github.com>:

**Comment by MarkoPaasila** [comment]
Ok good. I'll close this issue.
