### ISSUE TITLE
Nonetype with get_updated_limit_order

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#348]
```
2018-10-16 21:07:32,961 - NONE using account NONE on NONE - INFO - DEXBot 0.7.9 on python 3.5.4  win32
2018-10-16 21:07:37,536 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - Initializing Relative Orders
2018-10-16 21:07:37,536 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - "Reset orders on center price change" is active, placing fresh orders
2018-10-16 21:07:37,536 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - Canceling all orders
2018-10-16 21:07:37,650 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - Orders canceled
2018-10-16 21:07:38,190 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - Placing a buy order for 30.00233 BRIDGE.SNO @ 143019.09871232
2018-10-16 21:07:40,672 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - Placing a sell order for 3.859e-05 BRIDGE.BTC @ 150170.05364794
2018-10-16 21:07:43,369 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - Done placing orders
2018-10-16 21:07:47,371 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - Orders correct on market
2018-10-16 21:09:07,663 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - ERROR - in onMarketUpdate()
Traceback (most recent call last):
  File "dexbot\worker.py", line 142, in on_market
  File "site-packages\events-0.3-py3.5.egg\events\events.py", line 95, in __call__
  File "dexbot\strategies\relative_orders.py", line 377, in check_orders
  File "dexbot\strategies\relative_orders.py", line 279, in calculate_center_price
  File "dexbot\strategies\relative_orders.py", line 295, in calculate_asset_offset
  File "dexbot\strategies\base.py", line 460, in count_asset
  File "dexbot\strategies\base.py", line 488, in get_allocated_assets
  File "dexbot\strategies\base.py", line 937, in get_updated_order
  File "dexbot\strategies\base.py", line 1283, in get_updated_limit_order
TypeError: 'NoneType' object is not subscriptable
2018-10-16 21:10:00,276 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - Canceling all orders
2018-10-16 21:10:01,714 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - Orders canceled
2018-10-16 21:10:01,922 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - Initializing Relative Orders
2018-10-16 21:10:01,937 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - "Reset orders on center price change" is active, placing fresh orders
2018-10-16 21:10:01,937 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - Canceling all orders
2018-10-16 21:10:02,044 - Worker 1 REL using account kaptajn-kemo on BRIDGE.BTC/BRIDGE.SNO - INFO - Orders canceled
2018-10-16 21:10:02,373 - Worker 1 REL using account kaptajn-kemo on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "dexbot\worker.py", line 76, in init_workers
  File "dexbot\strategies\relative_orders.py", line 126, in __init__
  File "dexbot\strategies\relative_orders.py", line 207, in update_orders
  File "dexbot\strategies\relative_orders.py", line 184, in calculate_order_prices
  File "dexbot\strategies\relative_orders.py", line 279, in calculate_center_price
  File "dexbot\strategies\relative_orders.py", line 295, in calculate_asset_offset
  File "dexbot\strategies\base.py", line 460, in count_asset
  File "dexbot\strategies\base.py", line 488, in get_allocated_assets
  File "dexbot\strategies\base.py", line 937, in get_updated_order
  File "dexbot\strategies\base.py", line 1283, in get_updated_limit_order
TypeError: 'NoneType' object is not subscriptable
```

**Comment by bitfag** [comment]
It's probably my changes introduced a regression, I'm taking a look.

**Comment by bitfag** [comment]
OK the bug happening when `center_price_offset` option is `true` and order gets filled. calculate_center_price() takes saved .order_ids whereas order does not exists on market.
