### ISSUE TITLE
buy() got an unexpected keyword argument 'fee_asset'

### ISSUE THREAD

**Issue by Cobb-Chang** [Codaone/DEXBot#389]
## Expected Behavior
'
Traceback (most recent call last):
  File "/home/cobb/dexbot/dexbot/worker.py", line 76, in init_workers
    view=self.view
  File "/home/cobb/dexbot/dexbot/strategies/relative_orders.py", line 147, in __init__
    self.check_orders()
  File "/home/cobb/dexbot/dexbot/strategies/relative_orders.py", line 489, in check_orders
    self.update_orders()
  File "/home/cobb/dexbot/dexbot/strategies/relative_orders.py", line 314, in update_orders
    buy_order = self.place_market_buy_order(amount_base, self.buy_price, True)
  File "/home/cobb/dexbot/dexbot/strategies/base.py", line 1047, in place_market_buy_order
    **kwargs
  File "/home/cobb/dexbot/dexbot/strategies/base.py", line 1126, in retry_action
    return action(*args, **kwargs)
TypeError: buy() got an unexpected keyword argument 'fee_asset'
'

## Actual Behavior
Last time i run dexbot is ok. but tonight, while i run gui.py, i got this error.

## Specifications

  - Version:0.7.19
  - OS:ubuntu

**Comment by Cobb-Chang** [comment]
ive tried reinstall all module(resuirements.txt, python setup.py build & install) still not work

**Comment by bitfag** [comment]
@Cobb-Chang I'm sure you had some outdated version of python-bitshares. Please try latest dexbot release. If it will not help, try cleaning up old versions of python-bitshares manually. If you need assistance, join our telegram channel https://t.me/DEXBOTbts
