### ISSUE TITLE
Crash on pause worker

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#40]
Version 0.1.2, run from cli with `python3 ./app.py`

I created a new worker (Add bot) normally with:
- an existing account with both assets (BTS and USD)
- active private key
- dynamic price
- 2.0% spread

The bot created orders successfully. It crashed when I tried to pause worker with the message: `Muistialueen ylitys (luotiin core-tiedosto)`, which apparently translates to segmentation fault.

Next run it started successfully, and on "edit worker" it crashed with the message:
```
Traceback (most recent call last):
  File "/home/marko/localsoftware/DEXBot/dexbot/views/bot_item.py", line 95, in handle_edit_bot
    edit_bot_dialog = EditBotView(controller, self.botname, self.config)
  File "/home/marko/localsoftware/DEXBot/dexbot/views/edit_bot.py", line 25, in __init__
    center_price_dynamic = self.controller.get_target_center_price_dynamic(bot_data)
AttributeError: 'CreateBotController' object has no attribute 'get_target_center_price_dynamic'
Keskeytetty (luotiin core-tiedosto)
```
Using Archlinux with Gnome. Installed python dependencies manually with --user switch

**Comment by MarkoPaasila** [comment]
It appears that the "pause" results in a crash if there are no orders filled after starting/resuming the bot/worker. At least pause didn't cause a crash when there was one order filled.

**Comment by MarkoPaasila** [comment]
I'll close this as it's apparently just one of the many possible effects of an unclear installation procedure. At some point must attempt to make the installation fool-proof.
