### ISSUE TITLE
WrongMasterPasswordException

### ISSUE THREAD

**Issue by nextgenthemes** [Codaone/DEXBot#403]
## Expected Behavior
For it to work

## Actual Behavior
```
Traceback (most recent call last):
  File "site-packages/graphenelib-1.0.1-py3.6.egg/graphenestorage/masterpassword.py", line 104, in decryptEncryptedMaster
  File "site-packages/graphenelib-1.0.1-py3.6.egg/graphenebase/aes.py", line 47, in decrypt
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot/views/errors.py", line 95, in func_wrapper
  File "dexbot/views/create_wallet.py", line 20, in validate_form
  File "dexbot/controllers/wallet_controller.py", line 14, in create_wallet
  File "site-packages/bitshares-0.2.1-py3.6.egg/bitshares/wallet.py", line 145, in create
  File "site-packages/bitshares-0.2.1-py3.6.egg/bitshares/wallet.py", line 152, in newWallet
  File "site-packages/graphenelib-1.0.1-py3.6.egg/graphenestorage/masterpassword.py", line 93, in unlock
  File "site-packages/graphenelib-1.0.1-py3.6.egg/graphenestorage/masterpassword.py", line 106, in decryptEncryptedMaster
  File "site-packages/graphenelib-1.0.1-py3.6.egg/graphenestorage/masterpassword.py", line 113, in raiseWrongMasterPasswordException
graphenestorage.exceptions.WrongMasterPasswordException
```

## Steps to Reproduce the Problem

  1. Start binary
  2. type any pw twice

## Specifications

  - Version: https://github.com/Codaone/DEXBot/releases/download/0.7.25/DEXBot-gui-linux-0.7.25.tar.gz
  - OS:  Kubuntu 18.04

I actually had it working a few days ago but deleted the configs and wanted to start from scratch. I also find the docs confusing. Am I supposed to install it from git or just use the binary.

This might be just that I entered the wrong pw, wait no its asking to create a new wallet. I deleted all the files mentioned and strangely enough I just tried the Windows version and I get the very same thing. I just tested it out without filling in my real user and privatekey, it opened up and I could see the GUI then I deleted all files and run the .exe again and now I get the same error as on linux. Seems like its saving something elsewhere without mentioning where. How do I really delete everything?

**Comment by nextgenthemes** [comment]
I forgot to delete the bitshares.sqlite as well. Could have been a better error message.

**Comment by darkmaycal** [comment]
When i try to create new wallet: (Windows Python shell)    
raise WrongMasterPasswordException
graphenestorage.exceptions.WrongMasterPasswordException

**Comment by nnnarvaez** [comment]
cd ~
find ./ =name bitshares.sqlite
cd to resulting dir
delete bitshares.sqlite

**Comment by PermieBTS** [comment]
https://github.com/Codaone/DEXBot/wiki/Uptick-Wallet-Guide

**Comment by nnnarvaez** [comment]
> https://github.com/Codaone/DEXBot/wiki/Uptick-Wallet-Guide

my instructions are for linux  but thanks for pointing out to the windows solution

**Comment by PermieBTS** [comment]
Thanks for pointing out the linux instructions were missing from that wiki section, I've updated it
