### ISSUE TITLE
cannot placing order because of balance

### ISSUE THREAD

**Issue by foreman1** [Codaone/DEXBot#408]
Traceback (most recent call last):
  File "site-packages\graphenelib-1.0.1-py3.5.egg\grapheneapi\api.py", line 172, in func
  File "site-packages\graphenelib-1.0.1-py3.5.egg\grapheneapi\rpc.py", line 127, in method
  File "site-packages\graphenelib-1.0.1-py3.5.egg\grapheneapi\rpc.py", line 97, in parse_response
grapheneapi.exceptions.RPCError: Assert Exception: delta.amount > 0: Insufficient Balance: henezzo-1's balance of 0 BTC is less than required 0.00000002 BTC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot\strategies\base.py", line 300, in _cancel_orders
    orders, account=self.account, fee_asset=self.fee_asset['id']
  File "dexbot\strategies\base.py", line 1131, in retry_action
    return action(*args, **kwargs)
  File "site-packages\bitshares-0.2.1-py3.5.egg\bitshares\bitshares.py", line 1250, in cancel
  File "site-packages\bitshares-0.2.1-py3.5.egg\bitshares\bitshares.py", line 283, in finalizeOp
  File "site-packages\bitshares-0.2.1-py3.5.egg\bitshares\transactionbuilder.py", line 424, in broadcast
  File "site-packages\bitshares-0.2.1-py3.5.egg\bitshares\transactionbuilder.py", line 418, in broadcast
  File "site-packages\graphenelib-1.0.1-py3.5.egg\grapheneapi\api.py", line 180, in func
  File "site-packages\bitshares-0.2.1-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 19, in post_process_exception
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: delta.amount > 0: Insufficient Balance: henezzo-1's balance of 0 BTC is less than required 0.00000002 BTC

But i have much more than required ? what the problem somebody knows?

**Comment by bitfag** [comment]
Can you provide some log messages preceding mentioned tracebacks?

**Comment by foreman1** [comment]
![image](https://user-images.githubusercontent.com/45729175/49695481-84311500-fbbd-11e8-8004-a400e136983c.png)

you mean this log?

**Comment by bitfag** [comment]
No, please provide a dexbot.log, see https://github.com/Codaone/DEXBot/wiki/Common-problems#file-locations

**Comment by foreman1** [comment]
here my log
[dexbot.log](https://github.com/Codaone/DEXBot/files/2660412/dexbot.log)

**Comment by bitfag** [comment]
Looks like you just haven't enough Fee Asset to pay fees.
