### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by andresmoya** [Codaone/DEXBot#415]
Traceback (most recent call last):
  File "dexbot\worker.py", line 122, in on_block
  File "site-packages\events-0.3-py3.5.egg\events\events.py", line 95, in __call__
  File "dexbot\strategies\staggered_orders.py", line 1431, in tick
  File "dexbot\strategies\staggered_orders.py", line 207, in maintain_strategy
  File "dexbot\strategies\staggered_orders.py", line 532, in allocate_asset
  File "dexbot\strategies\staggered_orders.py", line 971, in check_partial_fill
  File "dexbot\strategies\base.py", line 954, in is_buy_order
TypeError: 'NoneType' object is not subscriptable

worker disables

## Steps to Reproduce the Problem

  1. turn on worker
  2. error happens

## Specifications

  - Version: 0.7.25
  - OS: windows 10

**Comment by bitfag** [comment]
Fixed in master branch, the fix will be included in next release.

**Comment by joelvai** [comment]
This issue is fixed in the latest release, in case this reoccurs please open new ticket.
