### ISSUE TITLE
Error starting worker (relative orders)

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#426]
## Steps to Reproduce the Problem

  1.updated to latest version
  2.changed worker from staggered to relative
  3.start worker
  4.receive error

## Specifications

  - Version:0.8.5
  - OS:ubuntu 16.04

I received the following error when trying to start a relative orders worker

Traceback (most recent call last):
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.8.5-py3.5.egg/dexbot/worker.py", line 76, in init_workers
    view=self.view
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.8.5-py3.5.egg/dexbot/strategies/relative_orders.py", line 92, in init
    self.center_price = self.get_external_market_center_price()
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.8.5-py3.5.egg/dexbot/strategies/base.py", line 620, in get_external_market_center_price
    center_price = price_feed.get_center_price(None)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.8.5-py3.5.egg/dexbot/strategies/external_feeds/price_feed.py", line 103, in get_center_price
    return self._get_center_price()
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.8.5-py3.5.egg/dexbot/strategies/external_feeds/price_feed.py", line 90, in _get_center_price
    price = get_ccxt_price(symbol, self._exchange)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.8.5-py3.5.egg/dexbot/strategies/external_feeds/ccxt_feed.py", line 40, in get_ccxt_price
    exchange = getattr(accxt, exchange_name)({'verbose': False})
TypeError: getattr(): attribute name must be string

**Comment by joelvai** [comment]
Did you set external price feed for the worker? If so and you are using Python `3.5.2` it doesn't work correctly. Only options are that you don't use external feed that uses ccxt or update your Python interpreter to `3.6`

**Comment by CryptoKong** [comment]
No i only use the gui i hadnt set any external price feeds. It was an old worker setup in a previous version which after updating i changed from staggered to relative then tried to run and got the error

**Comment by thehapax** [comment]
was this problem resolved? or it is still an outstanding error? @CryptoKong

**Comment by thehapax** [comment]
ok closing issue
