### ISSUE TITLE
bitshares/market.py: ValueError: could not convert string to float:

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#499]
This is a library issue but affects dexbot leading to "Worker xxx is disabled".

```
Traceback (most recent call last):
  File "/home/vvk/devel/DEXBot-prod/dexbot/worker.py", line 122, in on_block
    self.workers[worker_name].ontick(data)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-prod-N9mtHQyI/lib/python3.6/site-packages/Events-0.3-py3.6.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/vvk/devel/DEXBot-prod/dexbot/strategies/staggered_orders.py", line 1952, in tick
    self.maintain_strategy()
  File "/home/vvk/devel/DEXBot-prod/dexbot/strategies/staggered_orders.py", line 194, in maintain_strategy
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/home/vvk/devel/DEXBot-prod/dexbot/strategies/base.py", line 633, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/home/vvk/devel/DEXBot-prod/dexbot/strategies/base.py", line 678, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/home/vvk/.local/share/virtualenvs/DEXBot-prod-N9mtHQyI/lib/python3.6/site-packages/bitshares-0.2.1-py3.6.egg/bitshares/market.py", line 174, in ticker
    data["percentChange"] = float(ticker["percent_change"])
ValueError: could not convert string to float:
```

**Comment by bitfag** [comment]
Upstream issue: https://github.com/bitshares/python-bitshares/issues/186

**Comment by thehapax** [comment]
closed in latest release by @joelvai

**Comment by bitfag** [comment]
@joelvai did you applied any fixes for that? If no, please reopen the issue.

**Comment by bitfag** [comment]
This issue wasn't fixed yet.

**Comment by bitfag** [comment]
Fixed in bitshares-core https://github.com/bitshares/bitshares-core/issues/1620
