### ISSUE TITLE
bug in relative_orders.py

### ISSUE THREAD

**Issue by bitProfessor** [Codaone/DEXBot#525]
## Steps to Reproduce the Problem
relative_orders.py
1 When there is no order in the test node because there is no order in the market, Market. ticker () will make a mistake and the program will not catch it.Market. ticker ()，Many methods are used, like initialization methods.
2 When center_price is None, the program does not catch it.unsupported operand type(s) for /: ‘NoneType’ and ‘float’

## Specifications

  - Version:
  - OS:osx

**Comment by bitfag** [comment]
Please provide a full Traceback.

**Comment by bitProfessor** [comment]
(env) jackingdeMacBook-2:env jacking$ cd /Users/jacking/Documents/GitHub/env ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /Users/jacking/Documents/GitHub/env/bin/python3 /Users/jacking/.vscode/extensions/ms-python.python-2019.2.5558/pythonFiles/ptvsd_launcher.py --default --nodebug --client --host localhost --port 63804 /Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py 
test_configure (__main__.test_Strategy) ... ERROR
test_configure_details (__main__.test_Strategy) ... ERROR
test_error (__main__.test_Strategy) ... ERROR
test_tick (__main__.test_Strategy) ... ERROR
test_amount_to_sell (__main__.test_Strategy) ... ERROR
test_amount_to_buy (__main__.test_Strategy) ... ERROR
test_calculate_order_prices (__main__.test_Strategy) ... ERROR
test_update_orders (__main__.test_Strategy) ... ERROR
test_calculate_center_price (__main__.test_Strategy) ... ERROR
test_calculate_asset_offset (__main__.test_Strategy) ... ERROR
test_calculate_manual_offset (__main__.test_Strategy) ... ERROR
test_check_orders (__main__.test_Strategy) ... ERROR

======================================================================
ERROR: test_configure (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 51, in setUp
    self.relative_strategy=Strategy(name='dexbot-test1',config=TEST_CONFIG,bitshares_instance=self.bitShares)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 680, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/market.py", line 154, in ticker
    data["baseVolume"] = Amount(ticker["base_volume"], self["base"], blockchain_instance=self.blockchain)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/amount.py", line 116, in __init__
    self["amount"] = float(self["amount"])
ValueError: could not convert string to float: 

======================================================================
ERROR: test_configure_details (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 51, in setUp
    self.relative_strategy=Strategy(name='dexbot-test1',config=TEST_CONFIG,bitshares_instance=self.bitShares)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 680, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/market.py", line 154, in ticker
    data["baseVolume"] = Amount(ticker["base_volume"], self["base"], blockchain_instance=self.blockchain)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/amount.py", line 116, in __init__
    self["amount"] = float(self["amount"])
ValueError: could not convert string to float: 

======================================================================
ERROR: test_error (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 51, in setUp
    self.relative_strategy=Strategy(name='dexbot-test1',config=TEST_CONFIG,bitshares_instance=self.bitShares)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 680, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/market.py", line 154, in ticker
    data["baseVolume"] = Amount(ticker["base_volume"], self["base"], blockchain_instance=self.blockchain)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/amount.py", line 116, in __init__
    self["amount"] = float(self["amount"])
ValueError: could not convert string to float: 

======================================================================
ERROR: test_tick (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 51, in setUp
    self.relative_strategy=Strategy(name='dexbot-test1',config=TEST_CONFIG,bitshares_instance=self.bitShares)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 680, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/market.py", line 154, in ticker
    data["baseVolume"] = Amount(ticker["base_volume"], self["base"], blockchain_instance=self.blockchain)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/amount.py", line 116, in __init__
    self["amount"] = float(self["amount"])
ValueError: could not convert string to float: 

======================================================================
ERROR: test_amount_to_sell (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 51, in setUp
    self.relative_strategy=Strategy(name='dexbot-test1',config=TEST_CONFIG,bitshares_instance=self.bitShares)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 680, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/market.py", line 154, in ticker
    data["baseVolume"] = Amount(ticker["base_volume"], self["base"], blockchain_instance=self.blockchain)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/amount.py", line 116, in __init__
    self["amount"] = float(self["amount"])
ValueError: could not convert string to float: 

======================================================================
ERROR: test_amount_to_buy (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 51, in setUp
    self.relative_strategy=Strategy(name='dexbot-test1',config=TEST_CONFIG,bitshares_instance=self.bitShares)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 680, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/market.py", line 154, in ticker
    data["baseVolume"] = Amount(ticker["base_volume"], self["base"], blockchain_instance=self.blockchain)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/amount.py", line 116, in __init__
    self["amount"] = float(self["amount"])
ValueError: could not convert string to float: 

======================================================================
ERROR: test_calculate_order_prices (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 51, in setUp
    self.relative_strategy=Strategy(name='dexbot-test1',config=TEST_CONFIG,bitshares_instance=self.bitShares)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 680, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/market.py", line 154, in ticker
    data["baseVolume"] = Amount(ticker["base_volume"], self["base"], blockchain_instance=self.blockchain)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/amount.py", line 116, in __init__
    self["amount"] = float(self["amount"])
ValueError: could not convert string to float: 

======================================================================
ERROR: test_update_orders (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 51, in setUp
    self.relative_strategy=Strategy(name='dexbot-test1',config=TEST_CONFIG,bitshares_instance=self.bitShares)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 680, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/market.py", line 154, in ticker
    data["baseVolume"] = Amount(ticker["base_volume"], self["base"], blockchain_instance=self.blockchain)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/amount.py", line 116, in __init__
    self["amount"] = float(self["amount"])
ValueError: could not convert string to float: 

======================================================================
ERROR: test_calculate_center_price (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 51, in setUp
    self.relative_strategy=Strategy(name='dexbot-test1',config=TEST_CONFIG,bitshares_instance=self.bitShares)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 680, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/market.py", line 154, in ticker
    data["baseVolume"] = Amount(ticker["base_volume"], self["base"], blockchain_instance=self.blockchain)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/amount.py", line 116, in __init__
    self["amount"] = float(self["amount"])
ValueError: could not convert string to float: 

======================================================================
ERROR: test_calculate_asset_offset (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 51, in setUp
    self.relative_strategy=Strategy(name='dexbot-test1',config=TEST_CONFIG,bitshares_instance=self.bitShares)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 680, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/market.py", line 154, in ticker
    data["baseVolume"] = Amount(ticker["base_volume"], self["base"], blockchain_instance=self.blockchain)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/amount.py", line 116, in __init__
    self["amount"] = float(self["amount"])
ValueError: could not convert string to float: 

======================================================================
ERROR: test_calculate_manual_offset (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 51, in setUp
    self.relative_strategy=Strategy(name='dexbot-test1',config=TEST_CONFIG,bitshares_instance=self.bitShares)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 680, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/market.py", line 154, in ticker
    data["baseVolume"] = Amount(ticker["base_volume"], self["base"], blockchain_instance=self.blockchain)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/amount.py", line 116, in __init__
    self["amount"] = float(self["amount"])
ValueError: could not convert string to float: 

======================================================================
ERROR: test_check_orders (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 51, in setUp
    self.relative_strategy=Strategy(name='dexbot-test1',config=TEST_CONFIG,bitshares_instance=self.bitShares)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/base.py", line 680, in get_market_buy_price
    return float(self.ticker().get('highestBid'))
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/market.py", line 154, in ticker
    data["baseVolume"] = Amount(ticker["base_volume"], self["base"], blockchain_instance=self.blockchain)
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/bitshares/amount.py", line 116, in __init__
    self["amount"] = float(self["amount"])
ValueError: could not convert string to float: 

----------------------------------------------------------------------
Ran 12 tests in 19.822s

FAILED (errors=12)

**Comment by bitProfessor** [comment]
1、Deliberately looking for a market without any orders on testnode
2、return float(self.ticker().get('highestBid')) market.ticker() 。This condition was not addressed with python-bitshares.
sum: node wrong or a new market without any orders.

**Comment by bitfag** [comment]
#499

**Comment by thehapax** [comment]
@bitProfessor please update your release to 0.10.10 and rebuild and test. thanks
