### ISSUE TITLE
relative_orders.py test FAILED ,”self.buy_price “：The correct value may not be obtained.

### ISSUE THREAD

**Issue by bitProfessor** [Codaone/DEXBot#526]
## test data:
{'account': 'bts0207', 'amount': 1, 'center_price': 0.3, 'center_price_depth': 0.0, 'center_price_dynamic': True, 'center_price_offset': False, 'custom_expiration': False, 'dynamic_spread': False, 'dynamic_spread_factor': 1.0, 'expiration_time': 157680000.0, 'external_feed': False, 'external_price_source': 'null', 'fee_asset': 'BTS', 'manual_offset': 0.0, 'market': 'BTS/CNY', 'market_depth_amount': 0.0, 'module': 'dexbot.strategies.relative_orders', 'partial_fill_threshold': 30.0, 'price_change_threshold': 2.0, 'relative_order_size': False, 'reset_on_partial_fill': True, 'reset_on_price_change': False, 'spread': 5.0}
  1.======================================================================
ERROR: test_amount_to_sell (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 99, in test_amount_to_sell
    amount_to_sell=self.relative_strategy.amount_to_sell
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 184, in amount_to_sell
    amount * self.sell_price < 2 * 10 ** -self.market['base']['precision']):
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

2.======================================================================
ERROR: test_amount_to_buy (__main__.test_Strategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jacking/Documents/GitHub/env/DEXBot/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py", line 101, in test_amount_to_buy
    amount_to_buy=self.relative_strategy.amount_to_buy
  File "/Users/jacking/Documents/GitHub/env/lib/python3.7/site-packages/dexbot-0.9.19-py3.7.egg/dexbot/strategies/relative_orders.py", line 200, in amount_to_buy
    amount * self.buy_price < 2 * 10 ** -self.market['base']['precision']):
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

## Specifications
1. ”self.buy_price “：The correct value may not be obtained.
2.https://github.com/bitProfessor/DEXBot/blob/devel/test_dexbots/test_dexbot/test_strategies/test_relative_orders.py
 - Version:
  - OS:osx

**Comment by PermieBTS** [comment]
@thehapax

**Comment by thehapax** [comment]
this appears to be related to #499, please update to dexbot 0.10.1 latest release

**Comment by bitProfessor** [comment]
get it
