### ISSUE TITLE
can not add worker

### ISSUE THREAD

**Issue by hiquanta** [Codaone/DEXBot#53]
Traceback (most recent call last):
  File "/home/hiquanta/Documents/git/DEXBot/dexbot/views/create_worker.py", line 90, in handle_save
    if not self.validate_form():
  File "/home/hiquanta/Documents/git/DEXBot/dexbot/views/create_worker.py", line 75, in validate_form
    if not self.validate_account():
  File "/home/hiquanta/Documents/git/DEXBot/dexbot/views/create_worker.py", line 54, in validate_account
    return self.controller.is_account_valid(account, private_key)
  File "/home/hiquanta/Documents/git/DEXBot/dexbot/controllers/create_worker_controller.py", line 63, in is_account_valid
    pubkey = format(PrivateKey(private_key).pubkey, self.bitshares.prefix)
AttributeError: 'BitShares' object has no attribute 'prefix'

**Comment by mikakoi** [comment]
I've come across this issue previously but I've never been able to reproduce it. Are you able to reproduce this bug?

**Comment by hiquanta** [comment]
uninstall pyenv use sytem python3 will work
