### ISSUE TITLE
Is log written in installation dir?

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#540]
## Expected Behavior
Bot starts normally 

## Actual Behavior
`dexbot-cli -v4 run` gives me:
```
[marko@RPI-ARCH dexbot]$ dexbot-cli -v4 run
2019-04-07 09:38:00,746 INFO Using proxy None:80 http
Current Uptick Wallet Passphrase:
Traceback (most recent call last):
  File "/usr/bin/dexbot-cli", line 11, in <module>
    load_entry_point('dexbot', 'console_scripts', 'dexbot-cli')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/marko/dexbot/dexbot/ui.py", line 140, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/marko/dexbot/dexbot/ui.py", line 93, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/marko/dexbot/dexbot/ui.py", line 130, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/marko/dexbot/dexbot/ui.py", line 52, in new_func
    fh = logging.FileHandler(filename)
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/usr/bin/dexbot.log'

```

## Steps to Reproduce the Problem

  1. `git checkout master` and `git pull`
  2. Build current master with: `sudo pip3 install -e .`
  3. Run as non root with `dexbot-cli -v4 run`

## Specifications

  - Version: 0.10.1
  - OS: Arch Linux Arm

**Comment by bitfag** [comment]
Originated from #490
