### ISSUE TITLE
Cannot build in any Ubuntu environment

### ISSUE THREAD

**Issue by KenSharp** [Codaone/DEXBot#565]
> Supported Ubuntu versions: 16.04 LTS and newer (for now only tested on Ubuntu 16.04 LTS)

## Expected Behavior
The [Setup Guide for Ubuntu Linux](https://github.com/Codaone/DEXBot/wiki/Setup-Guide-for-Ubuntu-Linux) should make things incredibly easy to install.

## Actual Behavior
Ubuntu 16.04 in a virtualenv - fails
Ubuntu 18.04 - fails
Ubuntu 18.04 in a virtualenv - fails

From 16.04:
```
Collecting aiohttp==3.0.1 (from -r requirements.txt (line 6))
  Could not find a version that satisfies the requirement aiohttp==3.0.1 (from -r requirements.txt (line 6)) (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.21.4, 0.21.5, 0.21.6, 0.22.0a0, 0.22.0b0, 0.22.0b1, 0.22.0b2, 0.22.0b3, 0.22.0b4, 0.22.0b5, 0.22.0b6, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.22.4, 0.22.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.6.post1, 2.0.7, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0a1, 2.3.0a2, 2.3.0a4, 2.3.0, 2.3.1a1, 2.3.1, 2.3.2b2, 2.3.2b3, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 3.0.0b0)
No matching distribution found for aiohttp==3.0.1 (from -r requirements.txt (line 6))
Makefile:22: recipe for target 'pip-user' failed
make: *** [pip-user] Error 1
```

## Steps to Reproduce the Problem

  1. Follow the Setup Guide
  2. Tear out hair.

## Specifications

  - Version: Master?
  - OS: Ubuntu 16.04/18.04

**Comment by PermieBTS** [comment]
Ill ask one of our devs to take a look at your issue

Have you posted in the t.me/DEXBotbts telegram group? Will get a faster response in there

**Comment by bitfag** [comment]
I checked Ubuntu 18.04 installation by running docker image build (we have unfinished #433 and #439 PR related to it). No issues found.

Ubuntu 16.04 is not actually supported as we bumped required python version to 3.6.

**Comment by KenSharp** [comment]
Brand new system, brand new installation:

```
$ ~/.local/bin/dexbot-gui
Traceback (most recent call last):
  File "/home/ken/.local/bin/dexbot-gui", line 11, in <module>
    load_entry_point('dexbot==0.11.12', 'console_scripts', 'dexbot-gui')()
  File "/tmp/dexbot/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/dexbot/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/tmp/dexbot/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/tmp/dexbot/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ken/.local/lib/python3.6/site-packages/dexbot-0.11.12-py3.6.egg/dexbot/gui.py", line 4, in <module>
  File "/home/ken/.local/lib/python3.6/site-packages/dexbot-0.11.12-py3.6.egg/dexbot/controllers/main_controller.py", line 8, in <module>
  File "/home/ken/.local/lib/python3.6/site-packages/dexbot-0.11.12-py3.6.egg/dexbot/views/errors.py", line 5, in <module>
ModuleNotFoundError: No module named 'dexbot.views.ui.error_dialog_ui'
```

The cli seems to work okay but I haven't fully set it up yet.

**Comment by bitfag** [comment]
Please show `echo $PATH`

**Comment by bitfag** [comment]
Someone get such an issue in telegram group, the problem was OOM kill (see `dmesg | tail`) due to not enough memory on VPS.

**Comment by KenSharp** [comment]
I'm not using a VPS and have 16 GB so I doubt very much that that is the problem.

I'll look at this again later, when I get the chance. I haven't used it for a while.

**Comment by bitfag** [comment]
Ok, collect full install log next time please.
