### ISSUE TITLE
Clean exit for dexbot-cli run, not error thrown

### ISSUE THREAD

**Issue by thehapax** [Codaone/DEXBot#594]
## Expected Behavior
Would like to see a clean exit when exiting `dexbot-cli run`

## Actual Behavior
On exiting `dexbot-cli run` with control-x, control-c?
```
'NoneType' object has no attribute 'connected'
Traceback (most recent call last):
  File "/Users/octomatic/Library/Python/3.7/lib/python/site-packages/websocket/_app.py", line 305, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "/Users/octomatic/Library/Python/3.7/lib/python/site-packages/websocket/_app.py", line 63, in read
    while self.app.sock.connected:
AttributeError: 'NoneType' object has no attribute 'connected'
```
## Specifications

  - Version: current devel branch
  - OS: macOSX

**Comment by thehapax** [comment]
from Digital Lucifer - this was on windows, binary install of latest DEXBot
