### ISSUE TITLE
debot error

### ISSUE THREAD

**Issue by guaicaitu** [Codaone/DEXBot#646]
## Actual Behavior

http://wangzhuan.ren/image/error.png
## Steps to Reproduce the Problem
![错误](http://wangzhuan.ren/image/error.png)
登录的时候提示密码错误，不知道这个密码该怎么写，还有什么要注意的地方等。

## Specifications

  - Version: 0.13.3
  - OS: windows 10

**Comment by PermieBTS** [comment]
I am not sure what causes the issue, but re-installing and starting from scratch can solve it

Are you using the Windows Installer?

**Comment by guaicaitu** [comment]
> 我不确定是什么导致了这个问题，但重新安装并从头开始可以解决它
> 
> 您使用的是Windows Installer吗？

是的

**Comment by guaicaitu** [comment]
> 我不确定是什么导致了这个问题，但重新安装并从头开始可以解决它
> 
> 您使用的是Windows Installer吗？

已经重新安装了，但还是不行，报错如下：

Traceback (most recent call last):
  File "dexbot\views\errors.py", line 94, in func_wrapper
  File "dexbot\views\create_wallet.py", line 20, in validate_form
  File "dexbot\controllers\wallet_controller.py", line 14, in create_wallet
  File "site-packages\graphenecommon\wallet.py", line 145, in create
  File "site-packages\graphenecommon\wallet.py", line 152, in newWallet
  File "site-packages\graphenestorage\masterpassword.py", line 91, in unlock
  File "site-packages\graphenestorage\masterpassword.py", line 106, in _decrypt_masterpassword
  File "site-packages\graphenestorage\masterpassword.py", line 111, in _raise_wrongmasterpassexception
graphenestorage.exceptions.WrongMasterPasswordException

**Comment by PermieBTS** [comment]
I think the problem is the "uptick" wallet used to encrypt your dexbot-worker keys.

First, try using a longer password.

If that doesn't solve it, try this:

https://github.com/Codaone/DEXBot/wiki/Config-File-Locations
**Uptick

    Wallet: C:\Users\<user>\AppData\Local\Fabian Schuh\bitshares\bitshares.sqlite**


Steps to solve:
Close DEXBot application
On windows, press windows key, 
type "run", 
Open windows tool "run" and type "%Appdata%" into the box, press enter
Go to AppData/Local
Click "Fabian Schuh" folder
Get to the "bitshares.sqlite" file and delete this file

Run DEXBot again and it will ask for a new uptick password
