### ISSUE TITLE
Error when adding new worker

### ISSUE THREAD

**Issue by PermieBTS** [Codaone/DEXBot#647]
## Expected Behavior
Open add worker config, enter settings, press save. Saved

## Actual Behavior
Open add worker config, enter settings, press save. Error: 
Traceback (most recent call last):
  File "dexbot\views\errors.py", line 94, in func_wrapper
  File "dexbot\controllers\worker_controller.py", line 141, in validate_form
  File "dexbot\config_validator.py", line 48, in validate_private_key
  File "site-packages\graphenebase\account.py", `line 99, in init`
  File "site-packages\graphenebase\base58.py", `line 46, in init`
  File "site-packages\graphenebase\base58.py", line 168, in base58CheckDecode
AssertionError

  - Version: 0.13.3
  - OS: Windows

Looks like a private key error to me. I reproduced it by typing a valid but incorrect private active key, and got the exact same error except the   File "site-packages\graphenebase\account.py", line **399**, in __init__ 
(As opposed to line 99 in the user error above)

**Comment by bitfag** [comment]
Tried to reproduce on linux, got "Private key is invalid" error from the dexbot.
