### ISSUE TITLE
Latest docker build fails when running `dexbot-cli configure`

### ISSUE THREAD

**Issue by apaulb** [Codaone/DEXBot#660]
## Expected Behavior
Open the interactive configuration tool

## Actual Behavior
```
Traceback (most recent call last):
  File "/home/dexbot/.local/bin/dexbot-cli", line 11, in <module>
    load_entry_point('dexbot==0.15.4', 'console_scripts', 'dexbot-cli')()
  File "/home/dexbot/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/dexbot/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/dexbot/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/dexbot/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.4-py3.6.egg/dexbot/cli.py", line 9, in <module>
    from dexbot.cli_conf import SYSTEMD_SERVICE_NAME, get_whiptail, setup_systemd
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.4-py3.6.egg/dexbot/cli_conf.py", line 27, in <module>
    from dexbot.strategies.base import StrategyBase
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.4-py3.6.egg/dexbot/strategies/base.py", line 6, in <module>
    from dexbot.storage import Storage
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.4-py3.6.egg/dexbot/storage.py", line 497, in <module>
    db_worker = DatabaseWorker()
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.4-py3.6.egg/dexbot/storage.py", line 232, in __init__
    self.run_migrations(migrations_dir, dsn)
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.4-py3.6.egg/dexbot/storage.py", line 252, in run_migrations
    alembic.command.upgrade(alembic_cfg, 'head')
  File "/home/dexbot/.local/lib/python3.6/site-packages/alembic/command.py", line 256, in upgrade
    script = ScriptDirectory.from_config(config)
  File "/home/dexbot/.local/lib/python3.6/site-packages/alembic/script/base.py", line 145, in from_config
    timezone=config.get_main_option("timezone"),
  File "/home/dexbot/.local/lib/python3.6/site-packages/alembic/script/base.py", line 67, in __init__
    "scripts folder." % dir
alembic.util.exc.CommandError: Path doesn't exist: '/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.4-py3.6.egg/dexbot/migrations'.  Please use the 'init' command to create a new scripts folder.
```

## Steps to Reproduce the Problem

  1. ```mkdir dexbot-data dexbot-config```
  2. ```docker run -it --rm -v `pwd`/dexbot-config:/home/dexbot/.config/dexbot -v `pwd`/dexbot-data:/home/dexbot/.local/share dexbot/dexbot:latest dexbot-cli configure```

## Specifications

  - Version: 0.15.4

**Comment by bitfag** [comment]
Fixed in latest release 0.15.5

**Comment by apaulb** [comment]
This is actually not resolved with the latest release. But it throws a different error.
```
2019-08-21 20:24:21,680 INFO Context impl SQLiteImpl.
2019-08-21 20:24:21,681 INFO Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/home/dexbot/.local/bin/dexbot-cli", line 11, in <module>
    load_entry_point('dexbot==0.15.5', 'console_scripts', 'dexbot-cli')()
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.5-py3.6.egg/dexbot/ui.py", line 168, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.5-py3.6.egg/dexbot/ui.py", line 102, in new_func
    if ping(host_ip, 3) is False:
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.5-py3.6.egg/dexbot/node_manager.py", line 43, in ping
    subprocess.run(args, check=True, shell=False)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ping': 'ping'
```

**Comment by bitfag** [comment]
@apaulb thanks, this is another issue, I opened a separate issue.
