### ISSUE TITLE
dexbot failed to ping node in docker

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#664]
This is actually not resolved with the latest release. But it throws a different error.
```
2019-08-21 20:24:21,680 INFO Context impl SQLiteImpl.
2019-08-21 20:24:21,681 INFO Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/home/dexbot/.local/bin/dexbot-cli", line 11, in <module>
    load_entry_point('dexbot==0.15.5', 'console_scripts', 'dexbot-cli')()
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.5-py3.6.egg/dexbot/ui.py", line 168, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.5-py3.6.egg/dexbot/ui.py", line 102, in new_func
    if ping(host_ip, 3) is False:
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.15.5-py3.6.egg/dexbot/node_manager.py", line 43, in ping
    subprocess.run(args, check=True, shell=False)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ping': 'ping'
```

_Originally posted by @apaulb in https://github.com/Codaone/DEXBot/issues/660#issuecomment-523635282_

**Comment by bitfag** [comment]
dexbot tries to ping host via invoking `ping` utility which is not present in docker. I'd rather used a native python implementation like [pyping](https://pypi.org/project/pyping/). @thehapax what do you think?

**Comment by g3d** [comment]
Have same issue, can update Dockerfile for now until code is updates with new dependencies

**Comment by thehapax** [comment]
pyping is not supported for python3. Multiping exists as a package but requires the root access (doesn't seem like a good idea to use) 

The other option is to use just something very simple like sockets to check connection. Example:

```
import socket

ip_addr = "8.8.8.8"
try:
    response = socket.gethostbyaddr(ip_addr)
    print(response)
except socket.herror:
    print("Unknown host")```

**Comment by thehapax** [comment]
Alternative socket option to check connection:

```
import socket # for socket                                                                                
import sys                                                                                                
                                                                                                          
try:                                                                                                      
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)                                                 
    print("Socket successfully created")                                                                  
except socket.error as err:                                                                               
    print("socket creation failed with error %s" %(err))                                                  
                                                                                                          
# default port for socket                                                                                 
port = 80                                                                                                 
                                                                                                          
try:                                                                                                      
    host_ip = socket.gethostbyname('www.google.com')                                                      
except socket.gaierror:                                                                                   
    # this means could not resolve the host                                                               
    print("there was an error resolving the host")                                                        
    sys.exit()                                                                                            
                                                                                                          
# connecting to the server                                                                                
s.connect((host_ip,port))  
```

**Comment by bitfag** [comment]
What if particular IP / hostname is unavailable like blocked by ISP firewall? E.g. google IPs could be unavailable (including 8.8.8.8), but some bitshares nodes will be still accessible? Isn't it better to just check each node without mandatory 8.8.8.8 availability check?

**Comment by thehapax** [comment]
Would you prefer we use the Dns Resolver, 1.1.1.1? 

Here are some other options:
https://etherealmind.com/what-is-the-best-ip-address-to-ping-to-test-my-internet-connection/

And there is global redundancy for 1.1.1.1:
https://blog.cloudflare.com/dns-resolver-1-1-1-1/

Since this bug was about ping not available in docker os, I will issue a pull and we can debate the IP elsewhere. 

The utility of having a single IP ping method I believe is still useful,  instead of just querying all of the nodes and waiting a long time if user is not connected to the internet.

**Comment by bitfag** [comment]
Maybe just check if DNS resolving works at all (using system nameservers). Non-working resolving usually indicates connectivity problem.
