### ISSUE TITLE
DEXBot GUI fails on start (Linux)

### ISSUE THREAD

**Issue by svdev** [Codaone/DEXBot#686]
## Expected Behavior
Correct DEXBot GUI Initialization (Linux)

## Actual Behavior

DEXBot GUI initialization fails (see error below):

Traceback (most recent call last):                                                                                                                             
  File "dexbot/gui.py", line 33, in <module>                                                                                                                   
  File "dexbot/gui.py", line 28, in main                                                                                                                       
  File "dexbot/gui.py", line 15, in __init__                                                                                                                   
  File "dexbot/config.py", line 43, in __init__                                                                                                                
TypeError: get_sorted_nodelist() missing 1 required positional argument: 'timeout'
[25506] Failed to execute script gui

## Steps to Reproduce the Problem

  1. Download https://github.com/Codaone/DEXBot/releases/download/0.15.5/DEXBot-gui-linux-0.15.5.tar.gz
  2. tar -xzvf DEXBot*.gz
  3. ./DEXBot-gui

## Specifications

  - Version:  0.15.5
  - OS:        Arch Linux

**Comment by PermieBTS** [comment]
I think perhaps this to do with some nodes still being offline after the bug in the blockchain that was fixed a few days ago. 

Have you tried installing on linux using the terminalhttps://github.com/Codaone/DEXBot/wiki/Setup-Guide-for-Ubuntu-Linux with this guide?

**Comment by svdev** [comment]
@PermieBTS 

The issue is that the 'timeout' argument is missing when calling get_sorted_list() from config.py (line 43). See line reference:

https://github.com/Codaone/DEXBot/blob/5131f0b26da2624e2f8a3f01d1bf9778a1b8c54a/dexbot/config.py#L43

**Comment by PermieBTS** [comment]
Are you able to assist in the next few days @thehapax ?
They developed the node sorting
