### ISSUE TITLE
Update to current upstream libraries to fix "Execution error"

### ISSUE THREAD

**Issue by PermieBTS** [Codaone/DEXBot#692]
Execution error on a specific worker, then worker is disabled.

Seems not to be a node error

10 workers active, only 1 gets disabled.

**Comment by bitfag** [comment]
I assume this is related to George's error

```
Traceback (most recent call last):
  File "/home/dexbot/.local/lib/python3.6/site-packages/grapheneapi/api.py", line 168, in func
    r = func(*args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/grapheneapi/rpc.py", line 138, in method
    message = self.parse_response(r)
  File "/home/dexbot/.local/lib/python3.6/site-packages/grapheneapi/rpc.py", line 106, in parse_response
    raise RPCError(ret["error"]["message"])
grapheneapi.exceptions.RPCError: Execution error

```

Here "Execution error" is a response from API node, though there is no full node answer so we're don't see what exactly was wrong. This was fixed in recent version of graphenelib xeroc/python-graphenelib@1026f722bc1d7a3130014ce2c08cc2845d8a05bd so we're need to update our library versions.

**Comment by bitfag** [comment]
Need to update bitshares libraries to see full error.
