### ISSUE TITLE
Order fills just before it is cancelled. Worker jams.

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#73]
When using a small spread (0.40%) orders get filled very quickly. It happened that an order was filled, and the bot attempted to cancel the opposite order. The opposite order was filled before the "cancel order" reached the blockchain, and the bot couldn't cancel it.

This can be reproduced easily in an active market (BTS:USD) with a small spread (<0.4%).

Console output:
```
Error in on_market: Assert Exception: maybe_found != nullptr: Unable to find Object

Traceback (most recent call last):
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
    return self.rpc.rpcexec(self, payload)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: maybe_found != nullptr: Unable to find Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dexbotmake/dexbot/dexbot/worker.py", line 134, in on_market
    self.workers[worker_name].onMarketUpdate(data)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/dexbotmake/dexbot/dexbot/strategies/relative_orders.py", line 149, in check_orders
    self.update_orders()
  File "/home/dexbotmake/dexbot/dexbot/strategies/relative_orders.py", line 81, in update_orders
    self.cancel_all()
  File "/home/dexbotmake/dexbot/dexbot/basestrategy.py", line 266, in cancel_all
    account=self.account
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/bitshares.py", line 1202, in cancel
    return self.finalizeOp(op, account["name"], "active", **kwargs)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/bitshares.py", line 293, in finalizeOp
    return self.txbuffer.broadcast()
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 388, in broadcast
    raise e
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 386, in broadcast
    ret, api="network_broadcast")
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 213, in method
    r = self.rpcexec(query)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 64, in rpcexec
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: maybe_found != nullptr: Unable to find Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
    return self.rpc.rpcexec(self, payload)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: maybe_found != nullptr: Unable to find Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/websocket.py", line 276, in on_message
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/websocket.py", line 276, in <listcomp>
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/notify.py", line 164, in process_market
    bitshares_instance=self.bitshares
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/dexbotmake/dexbot/dexbot/worker.py", line 136, in on_market
    self.workers[worker_name].error_onMarketUpdate(e)
  File "/home/dexbotmake/dexbot/dexbot/strategies/relative_orders.py", line 70, in error
    self.cancel_all()
  File "/home/dexbotmake/dexbot/dexbot/basestrategy.py", line 266, in cancel_all
    account=self.account
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/bitshares.py", line 1202, in cancel
    return self.finalizeOp(op, account["name"], "active", **kwargs)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/bitshares.py", line 293, in finalizeOp
    return self.txbuffer.broadcast()
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 388, in broadcast
    raise e
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 386, in broadcast
    ret, api="network_broadcast")
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 213, in method
    r = self.rpcexec(query)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 64, in rpcexec
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: maybe_found != nullptr: Unable to find Object
```
At this point I forced the bot to close:
```
^CTraceback (most recent call last):
  File "/home/dexbotmake/dexbot/dexbot/views/worker_item.py", line 61, in pause_worker
    self.main_ctrl.stop_worker(self.worker_name)
  File "/home/dexbotmake/dexbot/dexbot/controllers/main_controller.py", line 35, in stop_worker
    self.worker_manager.stop(worker_name)
  File "/home/dexbotmake/dexbot/dexbot/worker.py", line 169, in stop
    self.remove_market(worker_name)
  File "/home/dexbotmake/dexbot/dexbot/worker.py", line 194, in remove_market
    with self.config_lock:
KeyboardInterrupt
The X11 connection broke (error 1). Did the X11 server die?
```

Here's the dexbot.log snippet:
```
2018-04-12 13:08:37,295 - Worker 2 using account dexbot.info on BTS/USD - INFO - Change detected, updating orders
2018-04-12 13:08:42,207 - Worker 2 using account dexbot.info on BTS/USD - INFO - Placed a buy order for 4.733755 USD @ 0.13882062645248552
2018-04-12 13:08:45,785 - Worker 2 using account dexbot.info on BTS/USD - INFO - Placed a sell order for 46.864547 BTS @ 0.13937702174888825
2018-04-12 13:08:45,939 - Worker 2 using account dexbot.info on BTS/USD - INFO - Change detected, updating orders
2018-04-12 13:08:45,962 - Worker 2 using account dexbot.info on BTS/USD - INFO - Canceling all orders
2018-04-12 13:08:51,239 - Worker 2 using account dexbot.info on BTS/USD - INFO - Placed a buy order for 5.03871 USD @ 0.1388194300564363
2018-04-12 13:08:54,420 - Worker 2 using account dexbot.info on BTS/USD - INFO - Placed a sell order for 44.6740135 BTS @ 0.13937582055766448
2018-04-12 13:08:57,631 - Worker 1 using account btsusd-2 on BTS/USD - INFO - Change detected, updating orders
2018-04-12 13:08:57,653 - Worker 1 using account btsusd-2 on BTS/USD - INFO - Canceling all orders
2018-04-12 13:09:04,200 - Worker 1 using account btsusd-2 on BTS/USD - INFO - Placed a buy order for 23.551810000000003 USD @ 0.13665240179045424
2018-04-12 13:09:09,636 - Worker 1 using account btsusd-2 on BTS/USD - INFO - Placed a sell order for 78.57081500000001 BTS @ 0.13941305637207957
2018-04-12 13:09:09,720 - Worker 2 using account dexbot.info on BTS/USD - INFO - Change detected, updating orders
2018-04-12 13:09:09,748 - Worker 2 using account dexbot.info on BTS/USD - INFO - Canceling all orders
2018-04-12 13:09:16,993 - Worker 2 using account dexbot.info on BTS/USD - INFO - Placed a buy order for 4.7867750000000004 USD @ 0.13778997115947592
2018-04-12 13:09:21,505 - Worker 2 using account dexbot.info on BTS/USD - INFO - Placed a sell order for 46.488539 BTS @ 0.13834223557294076
2018-04-12 13:09:21,642 - Worker 2 using account dexbot.info on BTS/USD - INFO - Change detected, updating orders
2018-04-12 13:09:21,669 - Worker 2 using account dexbot.info on BTS/USD - INFO - Canceling all orders
2018-04-12 13:09:28,272 - Worker 2 using account dexbot.info on BTS/USD - INFO - Placed a buy order for 5.1081650000000005 USD @ 0.13847404289614598
2018-04-12 13:09:30,148 - Worker 2 using account dexbot.info on BTS/USD - INFO - Placed a sell order for 44.163795 BTS @ 0.13902904908009847
2018-04-12 13:09:30,209 - Worker 1 using account btsusd-2 on BTS/USD - INFO - Canceling all orders
2018-04-12 13:09:30,259 - Worker 2 using account dexbot.info on BTS/USD - INFO - Change detected, updating orders
2018-04-12 13:09:30,287 - Worker 2 using account dexbot.info on BTS/USD - INFO - Canceling all orders
2018-04-12 13:09:36,769 - Worker 2 using account dexbot.info on BTS/USD - INFO - Worker "Worker 2" is disabled
2018-04-12 13:09:36,773 - Worker 2 using account dexbot.info on BTS/USD - INFO - Worker "Worker 2" is disabled
2018-04-12 13:09:36,777 - Worker 2 using account dexbot.info on BTS/USD - INFO - Worker "Worker 2" is disabled
2018-04-12 13:09:36,780 - Worker 2 using account dexbot.info on BTS/USD - INFO - Worker "Worker 2" is disabled
```

**Comment by MarkoPaasila** [comment]
I'm just wondering if it's necessary to wait for confirmation? Maybe the lack of confirmation could just be logged, but otherwise ignored and assumed to have been confirmed. That way the strategy would have a glitch, but it would continue working. It's much more important to keep working than to ensure a strict procedure. A small loss could happen, but it is just as likely that the error will be profitable. However, the bot stopping will surely stop any further profits from being made.
