### ISSUE TITLE
[cli conf] ValueError: Unknown format code 'f' for object of type 'str'

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#742]
Reported for my fork but most probably applies to original DEXBot too.

>  deleted the config.yml file
and I wanted to add a new configuration via GUI (this time SO). After a few steps, this message appeared

```
dexbot@vm2:~$ docker run -it --rm -v `pwd`/dexbot-config-vvk:/home/dexbot/.config/dexbot -v `pwd`/dexbot-data-vvk:/home/dexbot/.local/share vvk123/dexbot:latest ./cli.py configure
2020-02-18 14:36:55,520 INFO Context impl SQLiteImpl.
2020-02-18 14:36:55,521 INFO Will assume non-transactional DDL.
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=55 time=17.8 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 17.887/17.887/17.887/0.000 ms
Current Uptick Wallet Passphrase:
/bin/sh: 1: systemctl: not found
Traceback (most recent call last):
  File "./cli.py", line 6, in <module>
    cli.main()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dexbot/dexbot/dexbot/ui.py", line 159, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dexbot/dexbot/dexbot/ui.py", line 110, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dexbot/dexbot/dexbot/ui.py", line 148, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dexbot/dexbot/dexbot/cli.py", line 133, in configure
    configure_dexbot(config, ctx)
  File "/home/dexbot/dexbot/dexbot/cli_conf.py", line 282, in configure_dexbot
    config['workers'] = {txt: configure_worker(whiptail, {}, bitshares_instance)}
  File "/home/dexbot/dexbot/dexbot/cli_conf.py", line 256, in configure_worker
    process_config_element(elem, whiptail, worker_config)
  File "/home/dexbot/dexbot/dexbot/cli_conf.py", line 106, in process_config_element
    txt = whiptail.prompt(title, template.format(worker_config.get(element.key, element.default)))
ValueError: Unknown format code 'f' for object of type 'str'
```

**Comment by bitfag** [comment]
Not reproducible.
