### ISSUE TITLE
RO + extfeeds in docker: No module named 'idna_ssl'

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#743]
Reported for my fork but probably applied to original DEXBot too, need to check.

```
dexbot@vm2:~$ docker run -it --rm -v `pwd`/dexbot-config-vvk:/home/dexbot/.config/dexbot -v `pwd`/dexbot-data-vvk:/home/dexbot/.local/share vvk123/dexbot:latest ./cli.py -v4 run
2020-02-18 14:06:00,906 INFO Context impl SQLiteImpl.
2020-02-18 14:06:00,907 INFO Will assume non-transactional DDL.
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=55 time=22.4 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 22.439/22.439/22.439/0.000 ms
Current Uptick Wallet Passphrase:
2020-02-18 14:06:03,429 (ui:71) - INFO - Dexbot version 0.19.2, logfile: /home/dexbot/.local/share/dexbot/dexbot.log
2020-02-18 14:06:03,615 (worker:83) - test3 - ERROR - Worker initialisation
Traceback (most recent call last):
  File "/home/dexbot/dexbot/dexbot/worker.py", line 70, in init_workers
    strategy_class = getattr(importlib.import_module(worker["module"]), 'Strategy')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dexbot/dexbot/dexbot/strategies/relative_orders.py", line 6, in <module>
    from dexbot.strategies.external_feeds.price_feed import PriceFeed
  File "/home/dexbot/dexbot/dexbot/strategies/external_feeds/price_feed.py", line 3, in <module>
    from dexbot.strategies.external_feeds.ccxt_feed import get_ccxt_price
  File "/home/dexbot/dexbot/dexbot/strategies/external_feeds/ccxt_feed.py", line 3, in <module>
    import ccxt.async_support as accxt
  File "/usr/local/lib/python3.6/dist-packages/ccxt/async_support/__init__.py", line 11, in <module>
    from ccxt.async_support.base.exchange import Exchange                   # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/ccxt/async_support/base/__init__.py", line 4, in <module>
    from ccxt.async_support.base import exchange
  File "/usr/local/lib/python3.6/dist-packages/ccxt/async_support/base/exchange.py", line 16, in <module>
    import aiohttp
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 32, in <module>
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import HeadersParser as HeadersParser
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/helpers.py", line 59, in <module>
    import idna_ssl
ModuleNotFoundError: No module named 'idna_ssl'
2020-02-18 14:06:03,625 (worker:93) - CRITICAL - No workers actually running
```

**Comment by bitfag** [comment]
Unable to reproduce in vanilla dexbot.
