### ISSUE TITLE
Can't delete one of the Workers

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#75]
Had 2 Workers. After a freeze and kill I started the bot and tried to delete the first worker. No success. Terminal output below:

```
QApplication: invalid style override passed, ignoring it.
Traceback (most recent call last):
  File "/home/dexbotmake/dexbot/dexbot/views/worker_item.py", line 92, in remove_widget_dialog
    self.remove_widget()
  File "/home/dexbotmake/dexbot/dexbot/views/worker_item.py", line 96, in remove_widget
    self.main_ctrl.remove_worker(self.worker_name)
  File "/home/dexbotmake/dexbot/dexbot/controllers/main_controller.py", line 51, in remove_worker
    WorkerInfrastructure.remove_offline_worker(config, worker_name)
  File "/home/dexbotmake/dexbot/dexbot/worker.py", line 207, in remove_offline_worker
    strategy.purge()
  File "/home/dexbotmake/dexbot/dexbot/basestrategy.py", line 272, in purge
    self.cancel_all()
  File "/home/dexbotmake/dexbot/dexbot/basestrategy.py", line 266, in cancel_all
    account=self.account
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/bitshares.py", line 1202, in cancel
    return self.finalizeOp(op, account["name"], "active", **kwargs)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/bitshares.py", line 292, in finalizeOp
    self.txbuffer.sign()
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 345, in sign
    raise MissingKeyError
bitshares.exceptions.MissingKeyError
```

After this I successfully deleted the second Worker and tried the first again with no success. It should probably be noted that I had just wiped the wallet with `uptick wipewallet`

**Comment by CryptoKong** [comment]
I had the same problem.
![delete worker](https://user-images.githubusercontent.com/33036236/38708670-4c42a6f2-3eaf-11e8-86bc-dffe585a25a1.png)

**Comment by mikakoi** [comment]
It should be noted that mixing cli commands with gui isn't recommended. What happened here is that the gui tried to cancel the orders of the account when the worker was removed, but couldn't because the accounts private key was wiped from the account. 

Fix for this is just to skip order canceling and remove the worker.
