### ISSUE TITLE
GUI Freeze

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#76]
Ubuntu 16.04, DEXBot 0.1.12, two Workers.

I paused one Worker (the first). dexbot.log records "Canceling all orders", after which nothing happens. The pointer in in a "clicking hand" over the whole window. Must force window to close, but something still remains running as command prompt doesn't reappear. Here dexbot.info output:

```
2018-04-12 18:43:44,259 - BTSUSD-2 using account btsusd-2 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "/home/dexbotmake/dexbot/dexbot/worker.py", line 74, in init_workers
    view=self.view
  File "/home/dexbotmake/dexbot/dexbot/strategies/relative_orders.py", line 37, in __init__
    self.check_orders()
  File "/home/dexbotmake/dexbot/dexbot/strategies/relative_orders.py", line 149, in check_orders
    self.update_orders()
  File "/home/dexbotmake/dexbot/dexbot/strategies/relative_orders.py", line 100, in update_orders
    returnOrderId="head"
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/market.py", line 436, in buy
    tx = self.bitshares.finalizeOp(order, account["name"], "active")
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/bitshares.py", line 293, in finalizeOp
    return self.txbuffer.broadcast()
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 382, in broadcast
    ret, api="network_broadcast")
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 213, in method
    r = self.rpcexec(query)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
    return self.rpc.rpcexec(self, payload)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 135, in rpcexec
    reply = self.ws.recv()
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_core.py", line 300, in recv
    opcode, data = self.recv_data()
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_core.py", line 317, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_core.py", line 330, in recv_data_frame
    frame = self.recv_frame()
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_core.py", line 364, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_core.py", line 434, in _recv
    return recv(self.sock, bufsize)
  File "/home/dexbotmake/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_socket.py", line 81, in recv
    bytes_ = sock.recv(bufsize)
KeyboardInterrupt
```

**Comment by MarkoPaasila** [comment]
I'll close this as the Worker isn't disabled as often any more after the "can't find object" bug was fixed.
