### ISSUE TITLE
RPCError (Order does not exist) - Retry - Same error - Worker disabled

### ISSUE THREAD

**Issue by abitmore** [Codaone/DEXBot#780]
Running staggered orders strategy, sometimes the bot gets stuck. Finally got a stack trace today, see below.
```
2021-05-11 17:00:47,160 - mm.bts-xbtc.abot-stag using account mm.bts-xbtc.abot on XBTSX.BTC/BTS - ERROR - in onAccountUpdate()
Traceback (most recent call last):
  File "/home/ubuntu/opt/python-3.9.1/lib/python3.9/site-packages/grapheneapi/api.py", line 179, in func
    r = func(*args, **kwargs)
  File "/home/ubuntu/opt/python-3.9.1/lib/python3.9/site-packages/grapheneapi/rpc.py", line 149, in method
    message = self.parse_response(r)
  File "/home/ubuntu/opt/python-3.9.1/lib/python3.9/site-packages/grapheneapi/rpc.py", line 117, in parse_response
    raise RPCError(ret["error"]["message"])
grapheneapi.exceptions.RPCError: Execution error: Order does not exist: Limit order 1.7.468040261 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dexbot/dexbot/worker.py", line 180, in on_account
    self.workers[worker_name].onAccount(account_update)
  File "/home/ubuntu/opt/python-3.9.1/lib/python3.9/site-packages/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/ubuntu/dexbot/dexbot/decorators.py", line 21, in wrapper
    func(self, *args, **kwargs)
  File "/home/ubuntu/dexbot/dexbot/strategies/staggered_orders.py", line 197, in maintain_strategy
    trx = self.retry_action(self.execute)
  File "/home/ubuntu/dexbot/dexbot/orderengines/bitshares_engine.py", line 692, in retry_action
    return action(*args, **kwargs)
  File "/home/ubuntu/dexbot/dexbot/orderengines/bitshares_engine.py", line 510, in execute
    r = self.bitshares.txbuffer.broadcast()
  File "/home/ubuntu/opt/python-3.9.1/lib/python3.9/site-packages/graphenecommon/transactionbuilder.py", line 520, in broadcast
    raise e
  File "/home/ubuntu/opt/python-3.9.1/lib/python3.9/site-packages/graphenecommon/transactionbuilder.py", line 513, in broadcast
    ret = self.blockchain.rpc.broadcast_transaction_synchronous(
  File "/home/ubuntu/opt/python-3.9.1/lib/python3.9/site-packages/grapheneapi/api.py", line 187, in func
    self.post_process_exception(e)
  File "/home/ubuntu/opt/python-3.9.1/lib/python3.9/site-packages/bitsharesapi/bitsharesnoderpc.py", line 24, in post_process_exception
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Execution error: Order does not exist: Limit order 1.7.468040261 does not exist
2021-05-11 17:00:47,163 - mm.bts-xbtc.abot-stag using account mm.bts-xbtc.abot on XBTSX.BTC/BTS - ERROR - Worker "mm.bts-xbtc.abot-stag" is disabled
```

**Comment by abitmore** [comment]
This is due to a bitshares-core change in year 2019 ([this commit](https://github.com/bitshares/bitshares-core/commit/eea889ddeca477b92a0c641f8a1debe377dd79c7#diff-edab347446b325691e8138c7540050714046e99caf5fd86a01b568d34190f5eeL134-R144) in https://github.com/bitshares/bitshares-core/pull/1875).

**Comment by abitmore** [comment]
The strategy expects "maybe_found != nullptr: Unable to find Object": https://github.com/Codaone/DEXBot/blob/6197f989dc01d4b3dfe48ede4ae2bf8d10970fd6/dexbot/strategies/staggered_orders.py#L205-L210

But got "Order does not exist".
