### ISSUE TITLE
Arch linux PKGBUILD

### ISSUE THREAD

**Issue by svdev** [Codaone/DEXBot#79]
Implementation of PKGBUILD for Arch linux

AUR package url: https://aur.archlinux.org/packages/dexbot/

**Comment by MarkoPaasila** [comment]
Still gives me:
```
$ dexbot-cli 
Traceback (most recent call last):
  File "/usr/bin/dexbot-cli", line 11, in <module>
    load_entry_point('dexbot==0.1.12', 'console_scripts', 'dexbot-cli')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/dexbot/cli.py", line 14, in <module>
    from dexbot.worker import WorkerInfrastructure
  File "/usr/lib/python3.6/site-packages/dexbot/worker.py", line 9, in <module>
    from dexbot.basestrategy import BaseStrategy
  File "/usr/lib/python3.6/site-packages/dexbot/basestrategy.py", line 6, in <module>
    from bitshares.price import FilledOrder, Order, UpdateCallOrder
ImportError: cannot import name 'UpdateCallOrder'
```
