### ISSUE TITLE
can not start work

### ISSUE THREAD

**Issue by hiquanta** [Codaone/DEXBot#82]
Traceback (most recent call last):
  File "/home/hiquanta/.local/bin/dexbot-gui", line 11, in <module>
    load_entry_point('dexbot==0.1.13', 'console_scripts', 'dexbot-gui')()
  File "/home/hiquanta/.local/lib/python3.6/site-packages/dexbot-0.1.13-py3.6.egg/dexbot/gui.py", line 37, in main
  File "/home/hiquanta/.local/lib/python3.6/site-packages/dexbot-0.1.13-py3.6.egg/dexbot/gui.py", line 18, in __init__
TypeError: 'NoneType' object is not subscriptable

**Comment by MarkoPaasila** [comment]
Which Operating System and which installation method?

**Comment by hiquanta** [comment]
ubuntu16.04  and  dexbot-gui

**Comment by hiquanta** [comment]
Do I have to check release version?

**Comment by mikakoi** [comment]
@hiquanta It seems like your config.yml is empty. Just paste this
```
node: wss://bitshares.openledger.info/ws
workers: {}
```
into `~/.config/dexbot/config.yml`

**Comment by hiquanta** [comment]
i put into it ,but coming a new error log  this:
Traceback (most recent call last):
  File "/home/hiquanta/.local/bin/dexbot-gui", line 11, in <module>
    load_entry_point('dexbot==0.1.14', 'console_scripts', 'dexbot-gui')()
  File "/home/hiquanta/.local/lib/python3.6/site-packages/dexbot-0.1.14-py3.6.egg/dexbot/gui.py", line 37, in main
  File "/home/hiquanta/.local/lib/python3.6/site-packages/dexbot-0.1.14-py3.6.egg/dexbot/gui.py", line 18, in __init__
  File "/home/hiquanta/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ruamel.yaml-0.15.37-py3.6-linux-x86_64.egg/ruamel/yaml/comments.py", line 702, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'node'

**Comment by hiquanta** [comment]
I found the reason. 
uninstall pyenv and use system python3 commond
