### ISSUE TITLE
Cant create worker after most recent update

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#84]
Error from terminal after clicking save on create worker page:

Traceback (most recent call last):
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.13-py3.5.egg/dexbot/views/create_worker.py", line 105, in handle_save
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.13-py3.5.egg/dexbot/views/create_worker.py", line 90, in validate_form
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.13-py3.5.egg/dexbot/views/create_worker.py", line 69, in validate_account
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.13-py3.5.egg/dexbot/controllers/create_worker_controller.py", line 63, in is_account_valid
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesbase/account.py", line 113, in __init__
    super(PrivateKey, self).__init__(*args, **kwargs)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/graphenebase/account.py", line 311, in __init__
    self._wif = Base58(wif)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/graphenebase/base58.py", line 51, in __init__
    self._hex = base58CheckDecode(data)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/graphenebase/base58.py", line 180, in base58CheckDecode
    assert(s[-4:] == checksum)
AssertionError

**Comment by CryptoKong** [comment]
typed`  pip3 install —upgrade cryptography` in terminal as advised by marko and it now works fine, perhaps this could be automated?

**Comment by MarkoPaasila** [comment]
I'll close this because it's so old.
