### ISSUE TITLE
Left 2 workers running over night one still running in the morning, other failed

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#85]
I left two workers running last night worker 1 is still placing orders this morning in the bts - open.btc market. worker 2 had no orders showing and there was the following message in terminal, when i tried to pause the worker, dexbot crashed:
[dexbot.log](https://github.com/Codaone/DEXBot/files/1922514/dexbot.log)

```
cryptokong@cryptokong-Intel-Z370:~$ cd dexbot
cryptokong@cryptokong-Intel-Z370:~/dexbot$ dexbot-gui
/home/cryptokong/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/graphenebase/ecdsa.py:187: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = private_key.signer(ec.ECDSA(hashes.SHA256()))
Error in on_market: Assert Exception: operations.size() > 0: A transaction must have at least one operation

Traceback (most recent call last):
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
    return self.rpc.rpcexec(self, payload)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: now <= trx.expiration: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.13-py3.5.egg/dexbot/worker.py", line 134, in on_market
    self.workers[worker_name].onMarketUpdate(data)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.13-py3.5.egg/dexbot/strategies/relative_orders.py", line 149, in check_orders
    self.update_orders()
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.13-py3.5.egg/dexbot/strategies/relative_orders.py", line 121, in update_orders
    returnOrderId="head"
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/market.py", line 513, in sell
    tx = self.bitshares.finalizeOp(order, account["name"], "active")
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/bitshares.py", line 293, in finalizeOp
    return self.txbuffer.broadcast()
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 388, in broadcast
    raise e
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 382, in broadcast
    ret, api="network_broadcast")
  File "/home/cryptokong/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 213, in method
    r = self.rpcexec(query)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 64, in rpcexec
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: now <= trx.expiration:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
    return self.rpc.rpcexec(self, payload)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: operations.size() > 0: A transaction must have at least one operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/websocket.py", line 276, in on_message
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/websocket.py", line 276, in <listcomp>
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/cryptokong/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/notify.py", line 159, in process_market
    bitshares_instance=self.bitshares
  File "/home/cryptokong/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.13-py3.5.egg/dexbot/worker.py", line 136, in on_market
    self.workers[worker_name].error_onMarketUpdate(e)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.13-py3.5.egg/dexbot/strategies/relative_orders.py", line 72, in error
    self.log.info(self.execute())
  File "/home/cryptokong/.local/lib/python3.5/site-packages/dexbot-0.1.13-py3.5.egg/dexbot/basestrategy.py", line 245, in execute
    r = self.bitshares.txbuffer.broadcast()
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 388, in broadcast
    raise e
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 382, in broadcast
    ret, api="network_broadcast")
  File "/home/cryptokong/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 213, in method
    r = self.rpcexec(query)
  File "/home/cryptokong/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 64, in rpcexec
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: operations.size() > 0: A transaction must have at least one operation
```

**Comment by wmbutler** [comment]
I have observed this on the OS X version as well. It pretty consistently fails after running for an hour or so.

**Comment by wmbutler** [comment]
I think more advanced logging would help mitigate this. I'm not sure how often the agent checks in, but it would be great to see a log entry every interval:

```
<datetime> Starting
<datetime> Buy x for n y posted
<datetime> Sell x for n y posted
<datetime> Complete
<datetime> Starting
<datetime> No actions
<datetime> Stopping
```

This would go a long way toward helping users understand what's going on in the background.

**Comment by MarkoPaasila** [comment]
Yes indeed. I think I will make an issue for improving the log with more relevant information.
