### ISSUE TITLE
No module named dexbot-gui in 0.1.14

### ISSUE THREAD

**Issue by gabev** [Codaone/DEXBot#87]
I wiped the folder of the previous dexbot 0.1.12 and did git clone the latest 0.1.14 version. Using the command:  make install -user  is giving me errors related to SSL.py library.
I used the command python3 setup.py install  --user .
It did finished the install without throwing errors Tried starting the program running : dexbot-gui ..No go ..Error is : 
 :ModuleNotFoundError: No module named 'dexbot.gui'

    gabriel@E1-522:~$ dexbot-gui
    Traceback (most recent call last):
    File "/home/gabriel/.local/bin/dexbot-gui", line 11, in <module>
    load_entry_point('dexbot==0.1.14', 'console_scripts', 'dexbot-gui')()
    File "/home/gabriel/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in 
    load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
    File "/home/gabriel/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in 
    load_entry_point
    return ep.load()
    File "/home/gabriel/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
    File "/home/gabriel/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/home/gabriel/.local/lib/python3.6/site-packages/dexbot-0.1.14-py3.6.egg/dexbot/gui.py", line 7, in 
    <module>
    File "/home/gabriel/.local/lib/python3.6/site-packages/dexbot-0.1.14- 
    py3.6.egg/dexbot/views/worker_list.py", line 3, in <module>
    ModuleNotFoundError: No module namIed 'dexbot.views.ui.worker_list_window_ui'

I run Ubuntu 17.10 with python 2.7 & 3.6
![image](https://user-images.githubusercontent.com/9032546/38949954-e5421782-42f8-11e8-9527-70d8ac88599b.png)

**Comment by mikakoi** [comment]
You need to run `python setup.py build` manually (This is done automatically by `make install`). Closing this now but we should make instructions for manual installation if make install doesn't work.
