### ISSUE TITLE
Error in on_market: 'for_sale'

### ISSUE THREAD

**Issue by hiquanta** [Codaone/DEXBot#89]
i place order success,but the terminal always print this:
Traceback (most recent call last):
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitsharesapi/websocket.py", line 276, in on_message
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitsharesapi/websocket.py", line 276, in <listcomp>
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/shes/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitshares/notify.py", line 144, in process_market
    blockchain_instance=self.blockchain
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitshares/price.py", line 487, in __init__
    {"amount": self["for_sale"],
KeyError: 'for_sale'

**Comment by deepeetoo** [comment]
This error comes from [price.py](https://github.com/bitshares/python-bitshares/blob/master/bitshares/price.py) in the [Python Library for BitShares](https://github.com/bitshares/python-bitshares), which DEXBot uses.

For me it only seems to occur when running on Ubuntu 16.04 in the Windows Subsystem for Linux on a Wn10 machine. No such error on an Ubuntu 16.04 VM.

**Comment by hiquanta** [comment]
upgrade this lib will fix bug :https://github.com/bitshares/python-bitshares
