### ISSUE TITLE
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

### ISSUE THREAD

**Issue by hiquanta** [Codaone/DEXBot#92]
close status: 31522
Traceback (most recent call last):
  File "/home/shes/.local/lib/python3.5/site-packages/dexbot-0.1.15-py3.5.egg/dexbot/views/worker_item.py", line 52, in start_worker
  File "/home/shes/.local/lib/python3.5/site-packages/dexbot-0.1.15-py3.5.egg/dexbot/controllers/main_controller.py", line 29, in create_worker
  File "/home/shes/.local/lib/python3.5/site-packages/dexbot-0.1.15-py3.5.egg/dexbot/worker.py", line 159, in add_worker
  File "/home/shes/.local/lib/python3.5/site-packages/dexbot-0.1.15-py3.5.egg/dexbot/worker.py", line 91, in update_notify
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitshares/notify.py", line 118, in reset_subscriptions
    self.websocket.reset_subscriptions(accounts,self.get_market_ids(markets),objects)
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitsharesapi/websocket.py", line 178, in reset_subscriptions
    self.__set_subscriptions()
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitsharesapi/websocket.py", line 181, in __set_subscriptions
    self.cancel_all_subscriptions()
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitsharesapi/websocket.py", line 388, in method
    r = self.rpcexec(query)
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitsharesapi/websocket.py", line 354, in rpcexec
    self.ws.send(json.dumps(payload, ensure_ascii=False).encode('utf8'))
  File "/home/shes/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_app.py", line 147, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/home/shes/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_core.py", line 240, in send
    return self.send_frame(frame)
  File "/home/shes/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_core.py", line 265, in send_frame
    l = self._send(data)
  File "/home/shes/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_core.py", line 430, in _send
    return send(self.sock, data)
  File "/home/shes/.local/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_socket.py", line 114, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

**Comment by mikakoi** [comment]
Little more information on what you were doing before this exception would be helpful.

**Comment by hiquanta** [comment]
add three bot  1.bts:cny  2.cny:bts  3.usd:bts ,when i start all ,the terminal print this.Does the DEXBot support multiple bot in this version?

**Comment by mikakoi** [comment]
Yes it does

**Comment by hiquanta** [comment]
i adulbt doubt that this log is the service problem , and i change the to local node . this version of bot can  not reconnect.

**Comment by MarkoPaasila** [comment]
connectivity things have changed since this bugreport, so I will close it. Please re-open if it re-occurs.
