### ISSUE TITLE
USD / BRIDGE.LTC

### ISSUE THREAD

**Issue by wmbutler** [Codaone/DEXBot#93]
Added Worker as shown:

![screen shot 2018-04-22 at 5 23 15 pm](https://user-images.githubusercontent.com/1254810/39100624-ff424d76-4651-11e8-8ad1-55193b751219.png)

Activated it:

![screen shot 2018-04-22 at 5 23 44 pm](https://user-images.githubusercontent.com/1254810/39100627-0c67cee0-4652-11e8-94f2-0c49d4fb130b.png)

No trades are issued. Account has $500 bitUSD in it. Private Key verified carefully by deleting and recreating worker.

It might be nice to add a console log to help us troubleshoot.

Thanks for your awesome work! I support your WP.

**Comment by mikakoi** [comment]
There should be a dexbot.log next to the executable, can you paste the contents here?

**Comment by MarkoPaasila** [comment]
The account has BTS (for fee's), some BRIDGE.LTC, but no USD. So apparently the issue is that the bot can't handle zero balances/order sizes.

**Comment by wmbutler** [comment]
Looks like there was enough BTS in my account to cover the trade. Might be good for the bot to know that and show on the GUI that I shouldn't be able to initiate the trade unless I have some amount of BTS in the account to cover fees.

```
2018-04-22 16:46:07,389 - Worker 1 using account billbutler-trade1 on OPEN.EOS/USD - INFO - Change detected, updating orders
2018-04-22 16:46:13,192 - Worker 1 using account billbutler-trade1 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: amount_to_sell.amount > 0: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot/worker.py", line 74, in init_workers
  File "dexbot/strategies/relative_orders.py", line 38, in __init__
  File "dexbot/strategies/relative_orders.py", line 148, in check_orders
  File "dexbot/strategies/relative_orders.py", line 99, in update_orders
  File "bitshares-0.1.14-py3.6.egg/bitshares/market.py", line 437, in buy
  File "bitshares-0.1.14-py3.6.egg/bitshares/bitshares.py", line 293, in finalizeOp
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 387, in broadcast
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 381, in broadcast
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 213, in method
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: amount_to_sell.amount > 0:
2018-04-22 16:54:26,358 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Change detected, updating orders
2018-04-22 16:54:30,480 - Worker 1 using account billbutler-trade1 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: amount_to_sell.amount > 0: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot/worker.py", line 74, in init_workers
  File "dexbot/strategies/relative_orders.py", line 38, in __init__
  File "dexbot/strategies/relative_orders.py", line 148, in check_orders
  File "dexbot/strategies/relative_orders.py", line 99, in update_orders
  File "bitshares-0.1.14-py3.6.egg/bitshares/market.py", line 437, in buy
  File "bitshares-0.1.14-py3.6.egg/bitshares/bitshares.py", line 293, in finalizeOp
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 387, in broadcast
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 381, in broadcast
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 213, in method
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: amount_to_sell.amount > 0:
2018-04-22 16:58:18,679 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Change detected, updating orders
2018-04-22 16:58:23,131 - Worker 1 using account billbutler-trade1 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: amount_to_sell.amount > 0: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot/worker.py", line 74, in init_workers
  File "dexbot/strategies/relative_orders.py", line 38, in __init__
  File "dexbot/strategies/relative_orders.py", line 148, in check_orders
  File "dexbot/strategies/relative_orders.py", line 99, in update_orders
  File "bitshares-0.1.14-py3.6.egg/bitshares/market.py", line 437, in buy
  File "bitshares-0.1.14-py3.6.egg/bitshares/bitshares.py", line 293, in finalizeOp
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 387, in broadcast
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 381, in broadcast
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 213, in method
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: amount_to_sell.amount > 0:
2018-04-22 16:58:38,968 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Change detected, updating orders
2018-04-22 17:00:42,141 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Change detected, updating orders
2018-04-22 17:00:49,085 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Placed a buy order for 248.86493 BTS @ 42.91496565424949
2018-04-22 17:00:51,694 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Placed a sell order for 3.37600525 OPEN.EOS @ 43.781934657365646
2018-04-22 17:01:46,059 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Canceling all orders
2018-04-22 17:02:31,375 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Change detected, updating orders
2018-04-22 17:02:39,920 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Placed a buy order for 199.091716 BTS @ 43.26401429031987
2018-04-22 17:02:45,993 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Placed a sell order for 2.7008042000000003 OPEN.EOS @ 43.48087651733902
2018-04-22 17:02:49,000 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Change detected, updating orders
2018-04-22 17:02:49,408 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Canceling all orders
2018-04-22 17:02:57,711 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Placed a buy order for 199.111558 BTS @ 43.264017123484024
2018-04-22 17:03:00,728 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Placed a sell order for 2.7003162 OPEN.EOS @ 43.48087936470449
2018-04-22 17:12:21,748 - Worker 2 using account billbutler-trade2 on BRIDGE.LTC/USD - INFO - Change detected, updating orders
2018-04-22 17:12:24,785 - Worker 2 using account billbutler-trade2 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: itr->get_balance() >= -delta: Insufficient Balance: billbutler-trade2's balance of 0 BTS is less than required 0.00578 BTS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot/worker.py", line 74, in init_workers
  File "dexbot/strategies/relative_orders.py", line 38, in __init__
  File "dexbot/strategies/relative_orders.py", line 148, in check_orders
  File "dexbot/strategies/relative_orders.py", line 99, in update_orders
  File "bitshares-0.1.14-py3.6.egg/bitshares/market.py", line 437, in buy
  File "bitshares-0.1.14-py3.6.egg/bitshares/bitshares.py", line 293, in finalizeOp
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 387, in broadcast
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 381, in broadcast
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 213, in method
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: itr->get_balance() >= -delta: Insufficient Balance: billbutler-trade2's balance of 0 BTS is less than required 0.00578 BTS
2018-04-22 17:15:49,272 - Worker 2 using account billbutler-trade2 on BRIDGE.LTC/USD - INFO - Change detected, updating orders
2018-04-22 17:15:51,816 - Worker 2 using account billbutler-trade2 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: itr->get_balance() >= -delta: Insufficient Balance: billbutler-trade2's balance of 0 BTS is less than required 0.00578 BTS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot/worker.py", line 74, in init_workers
  File "dexbot/strategies/relative_orders.py", line 38, in __init__
  File "dexbot/strategies/relative_orders.py", line 148, in check_orders
  File "dexbot/strategies/relative_orders.py", line 99, in update_orders
  File "bitshares-0.1.14-py3.6.egg/bitshares/market.py", line 437, in buy
  File "bitshares-0.1.14-py3.6.egg/bitshares/bitshares.py", line 293, in finalizeOp
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 387, in broadcast
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 381, in broadcast
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 213, in method
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: itr->get_balance() >= -delta: Insufficient Balance: billbutler-trade2's balance of 0 BTS is less than required 0.00578 BTS
2018-04-22 17:22:47,267 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Change detected, updating orders
2018-04-22 17:22:47,676 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Canceling all orders
2018-04-22 17:22:54,205 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Canceling all orders
2018-04-22 17:26:25,099 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Change detected, updating orders
2018-04-22 17:26:25,510 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Canceling all orders
2018-04-22 17:26:28,340 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Canceling all orders
2018-04-22 17:31:08,062 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Canceling all orders
2018-04-22 17:31:32,252 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Canceling all orders
2018-04-22 17:31:38,729 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Change detected, updating orders
2018-04-22 17:31:45,767 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Placed a buy order for 222.592712 BTS @ 43.41793670089568
2018-04-22 17:31:52,004 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Placed a sell order for 2.1602530000000004 OPEN.EOS @ 43.591956487272014
2018-04-22 17:32:01,721 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Change detected, updating orders
2018-04-22 17:32:02,116 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Canceling all orders
2018-04-22 17:32:12,723 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Placed a buy order for 219.76948400000006 BTS @ 43.41793755452143
2018-04-22 17:32:15,785 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Placed a sell order for 2.2251158 OPEN.EOS @ 43.59195734431911
2018-04-22 17:33:01,673 - Worker 2 using account billbutler-trade2 on BRIDGE.LTC/USD - INFO - Change detected, updating orders
2018-04-22 17:33:04,796 - Worker 2 using account billbutler-trade2 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: itr->get_balance() >= -delta: Insufficient Balance: billbutler-trade2's balance of 0 BTS is less than required 0.00578 BTS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot/worker.py", line 74, in init_workers
  File "dexbot/strategies/relative_orders.py", line 38, in __init__
  File "dexbot/strategies/relative_orders.py", line 148, in check_orders
  File "dexbot/strategies/relative_orders.py", line 99, in update_orders
  File "bitshares-0.1.14-py3.6.egg/bitshares/market.py", line 437, in buy
  File "bitshares-0.1.14-py3.6.egg/bitshares/bitshares.py", line 293, in finalizeOp
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 387, in broadcast
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 381, in broadcast
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 213, in method
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: itr->get_balance() >= -delta: Insufficient Balance: billbutler-trade2's balance of 0 BTS is less than required 0.00578 BTS
2018-04-22 17:37:32,731 - Worker 1 using account billbutler-trade1 on OPEN.EOS/BTS - INFO - Canceling all orders
2018-04-22 17:41:06,231 - Worker 2 using account billbutler-trade2 on BRIDGE.LTC/BTS - INFO - Change detected, updating orders
2018-04-22 17:41:13,009 - Worker 2 using account billbutler-trade2 on BRIDGE.LTC/BTS - INFO - Placed a buy order for 395.91699400000005 BTS @ 482.1304868054417
2018-04-22 17:41:15,011 - Worker 2 using account billbutler-trade2 on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: amount_to_sell.amount > 0: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot/worker.py", line 74, in init_workers
  File "dexbot/strategies/relative_orders.py", line 38, in __init__
  File "dexbot/strategies/relative_orders.py", line 148, in check_orders
  File "dexbot/strategies/relative_orders.py", line 120, in update_orders
  File "bitshares-0.1.14-py3.6.egg/bitshares/market.py", line 515, in sell
  File "bitshares-0.1.14-py3.6.egg/bitshares/bitshares.py", line 293, in finalizeOp
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 387, in broadcast
  File "bitshares-0.1.14-py3.6.egg/bitshares/transactionbuilder.py", line 381, in broadcast
  File "graphenelib-0.6.1-py3.6.egg/grapheneapi/graphenewsrpc.py", line 213, in method
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: amount_to_sell.amount > 0:
```
