### ISSUE TITLE
Unable to find object

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#96]
If I interpret things correctly, this error pops up after an order has happened and the bot intends to cancel the rest of the orders, and meanwhile the rest of the same order/the other order has filled and disappeared from the books.

```
2018-04-20 18:13:30,354 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Canceling all orders
2018-04-20 18:13:33,130 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Placed a buy order for 28.2677163 BTS @ 33449.72784296184
2018-04-20 18:13:36,112 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Placed a sell order for 0.0003252459 OPEN.BTC @ 33533.456823795284
2018-04-20 18:14:00,268 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Change detected, updating orders
2018-04-20 18:14:00,279 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Canceling all orders
2018-04-20 18:14:03,117 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Placed a buy order for 27.4194945 BTS @ 33446.27637079546
2018-04-20 18:14:06,880 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Placed a sell order for 0.00035054789999999997 OPEN.BTC @ 33529.996712149135
2018-04-20 18:14:06,956 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Change detected, updating orders
2018-04-20 18:14:06,969 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Canceling all orders
2018-04-20 18:14:09,546 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Canceling all orders
2018-04-20 18:14:10,017 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Worker "DEXBOT.INFO" is disabled
2018-04-20 18:14:10,039 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Worker "DEXBOT.INFO" is disabled
2018-04-20 18:14:10,044 - DEXBOT.INFO using account dexbot.info on OPEN.BTC/BTS - INFO - Worker "DEXBOT.INFO" is disabled



$ dexbot-gui
QApplication: invalid style override passed, ignoring it.
/home/marko/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/graphenebase/ecdsa.py:187: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = private_key.signer(ec.ECDSA(hashes.SHA256()))
nope
nope
nope
nope
Error in on_market: Assert Exception: maybe_found != nullptr: Unable to find Object

Traceback (most recent call last):
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
    return self.rpc.rpcexec(self, payload)
  File "/home/marko/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: maybe_found != nullptr: Unable to find Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marko/.local/lib/python3.5/site-packages/dexbot-0.1.14-py3.5.egg/dexbot/worker.py", line 134, in on_market
    self.workers[worker_name].onMarketUpdate(data)
  File "/home/marko/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/marko/.local/lib/python3.5/site-packages/dexbot-0.1.14-py3.5.egg/dexbot/strategies/relative_orders.py", line 148, in check_orders
    self.update_orders()
  File "/home/marko/.local/lib/python3.5/site-packages/dexbot-0.1.14-py3.5.egg/dexbot/strategies/relative_orders.py", line 99, in update_orders
    returnOrderId="head"
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/market.py", line 436, in buy
    tx = self.bitshares.finalizeOp(order, account["name"], "active")
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/bitshares.py", line 293, in finalizeOp
    return self.txbuffer.broadcast()
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 388, in broadcast
    raise e
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 382, in broadcast
    ret, api="network_broadcast")
  File "/home/marko/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 213, in method
    r = self.rpcexec(query)
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 64, in rpcexec
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: maybe_found != nullptr: Unable to find Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
    return self.rpc.rpcexec(self, payload)
  File "/home/marko/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: maybe_found != nullptr: Unable to find Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/websocket.py", line 276, in on_message
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/websocket.py", line 276, in <listcomp>
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/marko/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/notify.py", line 159, in process_market
    bitshares_instance=self.bitshares
  File "/home/marko/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/marko/.local/lib/python3.5/site-packages/dexbot-0.1.14-py3.5.egg/dexbot/worker.py", line 136, in on_market
    self.workers[worker_name].error_onMarketUpdate(e)
  File "/home/marko/.local/lib/python3.5/site-packages/dexbot-0.1.14-py3.5.egg/dexbot/strategies/relative_orders.py", line 71, in error
    self.log.info(self.execute())
  File "/home/marko/.local/lib/python3.5/site-packages/dexbot-0.1.14-py3.5.egg/dexbot/basestrategy.py", line 248, in execute
    r = self.bitshares.txbuffer.broadcast()
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 388, in broadcast
    raise e
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 382, in broadcast
    ret, api="network_broadcast")
  File "/home/marko/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 213, in method
    r = self.rpcexec(query)
  File "/home/marko/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 64, in rpcexec
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: maybe_found != nullptr: Unable to find Object
```

**Comment by mikakoi** [comment]
This was fixed a while back but I forgot to close this.
