### ISSUE TITLE
OS X Bug - Will not relaunch after crash

### ISSUE THREAD

**Issue by wmbutler** [Codaone/DEXBot#98]
I was running 2 workers. I paused one. Then I unpaused it. The OS X app forced quit. I attempted to relaunch. It asked for the password which I entered properly. The app never finished launching. It just existed to the Finder.

This happened on my home computer, a new MacBook and my work computer, an iMac 27", both with latest MacOS and >16GB RAM.

No entries in the logfile that look out of place other than submitting orders.

**Comment by wmbutler** [comment]
I was able to capture the log during the crash. I'm certain the keyfile was fine because it placed trades previously. I have 2 workers running so I wonder if it's mixing up the keyfiles...

```
BBUTLER-MAC:~ bbutler$ /Users/bbutler/Downloads/dist/osx/DEXBot-gui ; exit;
[60481] PyInstaller Bootloader 3.x
[60481] LOADER: executable is /Users/bbutler/Downloads/dist/osx/DEXBot-gui
[60481] LOADER: homepath is /Users/bbutler/Downloads/dist/osx
[60481] LOADER: _MEIPASS2 is NULL
[60481] LOADER: archivename is /Users/bbutler/Downloads/dist/osx/DEXBot-gui
[60481] LOADER: Extracting binaries
[60481] LOADER: Executing self as child
[60481] LOADER: set _MEIPASS2 to /var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEII5macO
[60482] PyInstaller Bootloader 3.x
[60482] LOADER: executable is /Users/bbutler/Downloads/dist/osx/DEXBot-gui
[60482] LOADER: homepath is /Users/bbutler/Downloads/dist/osx
[60482] LOADER: _MEIPASS2 is /var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEII5macO
[60482] LOADER: archivename is /Users/bbutler/Downloads/dist/osx/DEXBot-gui
[60482] LOADER: Already in the child - running user's code.
[60482] LOADER: Python library: /var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEII5macO/Python
[60482] LOADER: Loaded functions from Python library.
[60482] LOADER: Manipulating environment (sys.path, sys.prefix)
[60482] LOADER: Pre-init sys.path is /var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEII5macO/base_library.zip:/var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEII5macO
[60482] LOADER: sys.prefix is /var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEII5macO
[60482] LOADER: Setting runtime options
[60482] LOADER: Initializing python
[60482] LOADER: Overriding Python's sys.path
[60482] LOADER: Post-init sys.path is /var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEII5macO/base_library.zip:/var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEII5macO
[60482] LOADER: Setting sys.argv
[60482] LOADER: setting sys._MEIPASS
[60482] LOADER: importing modules from CArchive
[60482] LOADER: extracted struct
[60482] LOADER: callfunction returned...
[60482] LOADER: extracted pyimod01_os_path
[60482] LOADER: callfunction returned...
[60482] LOADER: extracted pyimod02_archive
[60482] LOADER: callfunction returned...
[60482] LOADER: extracted pyimod03_importers
[60482] LOADER: callfunction returned...
[60482] LOADER: Installing PYZ archive with Python modules.
[60482] LOADER: PYZ archive: out00-PYZ.pyz
[60482] LOADER: Running pyiboot01_bootstrap.py
[60482] LOADER: Running rthook-Crypto.py
[60482] LOADER: Running pyi_rth_multiprocessing.py
[60482] LOADER: Running pyi_rth_pkgres.py
[60482] LOADER: Running pyi_rth_qt5.py
[60482] LOADER: Running gui.py
Error in on_market: 'for_sale'

Traceback (most recent call last):
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/websocket.py", line 276, in on_message
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/websocket.py", line 276, in <listcomp>
  File "Events-0.3-py3.6.egg/events/events.py", line 95, in __call__
  File "bitshares-0.1.14-py3.6.egg/bitshares/notify.py", line 144, in process_market
  File "bitshares-0.1.14-py3.6.egg/bitshares/price.py", line 487, in __init__
KeyError: 'for_sale'

Error in on_market: 'for_sale'

Traceback (most recent call last):
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/websocket.py", line 276, in on_message
  File "bitshares-0.1.14-py3.6.egg/bitsharesapi/websocket.py", line 276, in <listcomp>
  File "Events-0.3-py3.6.egg/events/events.py", line 95, in __call__
  File "bitshares-0.1.14-py3.6.egg/bitshares/notify.py", line 144, in process_market
  File "bitshares-0.1.14-py3.6.egg/bitshares/price.py", line 487, in __init__
KeyError: 'for_sale'

Traceback (most recent call last):
  File "dexbot/views/worker_list.py", line 88, in customEvent
  File "dexbot/queue/idle_queue.py", line 8, in idle
  File "dexbot/views/worker_list.py", line 78, in set_worker_profit
KeyError: 'billbutler-trade2'
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...104 completed.
```

**Comment by wmbutler** [comment]
So, I was able to get the DEXBot-gui to relaunch after a crash but not the DexBot app with the icon. The crash generally seems to occur after I launch the second worker. Different error here:

```BBUTLER-MAC:~ bbutler$ /Users/bbutler/Downloads/dist/osx/DEXBot-gui ; exit;
[61894] PyInstaller Bootloader 3.x
[61894] LOADER: executable is /Users/bbutler/Downloads/dist/osx/DEXBot-gui
[61894] LOADER: homepath is /Users/bbutler/Downloads/dist/osx
[61894] LOADER: _MEIPASS2 is NULL
[61894] LOADER: archivename is /Users/bbutler/Downloads/dist/osx/DEXBot-gui
[61894] LOADER: Extracting binaries
[61894] LOADER: Executing self as child
[61894] LOADER: set _MEIPASS2 to /var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEIOdf3vo
[61895] PyInstaller Bootloader 3.x
[61895] LOADER: executable is /Users/bbutler/Downloads/dist/osx/DEXBot-gui
[61895] LOADER: homepath is /Users/bbutler/Downloads/dist/osx
[61895] LOADER: _MEIPASS2 is /var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEIOdf3vo
[61895] LOADER: archivename is /Users/bbutler/Downloads/dist/osx/DEXBot-gui
[61895] LOADER: Already in the child - running user's code.
[61895] LOADER: Python library: /var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEIOdf3vo/Python
[61895] LOADER: Loaded functions from Python library.
[61895] LOADER: Manipulating environment (sys.path, sys.prefix)
[61895] LOADER: Pre-init sys.path is /var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEIOdf3vo/base_library.zip:/var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEIOdf3vo
[61895] LOADER: sys.prefix is /var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEIOdf3vo
[61895] LOADER: Setting runtime options
[61895] LOADER: Initializing python
[61895] LOADER: Overriding Python's sys.path
[61895] LOADER: Post-init sys.path is /var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEIOdf3vo/base_library.zip:/var/folders/l9/8br70ybj3g9g6ttxk7hm4xcc0000gn/T/_MEIOdf3vo
[61895] LOADER: Setting sys.argv
[61895] LOADER: setting sys._MEIPASS
[61895] LOADER: importing modules from CArchive
[61895] LOADER: extracted struct
[61895] LOADER: callfunction returned...
[61895] LOADER: extracted pyimod01_os_path
[61895] LOADER: callfunction returned...
[61895] LOADER: extracted pyimod02_archive
[61895] LOADER: callfunction returned...
[61895] LOADER: extracted pyimod03_importers
[61895] LOADER: callfunction returned...
[61895] LOADER: Installing PYZ archive with Python modules.
[61895] LOADER: PYZ archive: out00-PYZ.pyz
[61895] LOADER: Running pyiboot01_bootstrap.py
[61895] LOADER: Running rthook-Crypto.py
[61895] LOADER: Running pyi_rth_multiprocessing.py
[61895] LOADER: Running pyi_rth_pkgres.py
[61895] LOADER: Running pyi_rth_qt5.py
[61895] LOADER: Running gui.py
Traceback (most recent call last):
  File "dexbot/views/worker_item.py", line 52, in start_worker
  File "dexbot/controllers/main_controller.py", line 29, in create_worker
  File "dexbot/worker.py", line 159, in add_worker
  File "dexbot/worker.py", line 91, in update_notify
  File "bitshares-0.1.14-py3.6.egg/bitshares/notify.py", line 118, in reset_subscriptions
  File "bitshares-0.1.14-py3.6.egg/bitshares/notify.py", line 107, in get_market_ids
  File "bitshares-0.1.14-py3.6.egg/bitshares/market.py", line 55, in __init__
  File "bitshares-0.1.14-py3.6.egg/bitshares/asset.py", line 33, in __init__
  File "bitshares-0.1.14-py3.6.egg/bitshares/blockchainobject.py", line 107, in __init__
  File "bitshares-0.1.14-py3.6.egg/bitshares/asset.py", line 51, in refresh
  File "bitshares-0.1.14-py3.6.egg/bitsharesbase/asset_permissions.py", line 30, in todict
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.


```

**Comment by MarkoPaasila** [comment]
Thanks for testing on osx. I'll let others figure out the problem :-)

**Comment by MarkoPaasila** [comment]
@wmbutler have you tested DEXBot lately? Does it work for you?

**Comment by MarkoPaasila** [comment]
This isn't probably relevant any more. I'll close it

**Comment by wmbutler** [comment]
I haven't recently. Sorry.
