### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by hiquanta** [Codaone/DEXBot#99]
when i start all bot the terminal log this and the window is freezen.
/home/shes/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/graphenebase/ecdsa.py:187: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = private_key.signer(ec.ECDSA(hashes.SHA256()))
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/shes/.local/lib/python3.5/site-packages/dexbot-0.1.15-py3.5.egg/dexbot/worker.py", line 162, in run
    self.init_workers(self.config)
  File "/home/shes/.local/lib/python3.5/site-packages/dexbot-0.1.15-py3.5.egg/dexbot/worker.py", line 52, in init_workers
    for worker_name, worker in config["workers"].items():
RuntimeError: dictionary changed size during iteration

**Comment by MarkoPaasila** [comment]
Did you have to force close the bot before this? To me it looks like force closing the frozen bot leaves it in a wrong state, and restarting once more fixes this.

**Comment by hiquanta** [comment]
Yes, I forcibly closed the bot and can work after restarting. I suspect that the apiService response time is too long, it is recommended to add multiple apiService, can automatically connect. Because not everyone will build their own node, the public node is very easy to go wrong
